<!DOCTYPE html>
<html class="client-nojs" lang="en" dir="ltr">

<!-- Mirrored from subpos.org/wiki/index.php?title=Coded_Beacon_Frame&action=history by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 07 Nov 2019 05:39:18 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
<head>
<meta charset="UTF-8"/>
<title>Revision history of "Coded Beacon Frame" - SubPos</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Coded_Beacon_Frame","wgTitle":"Coded Beacon Frame","wgCurRevisionId":516,"wgRevisionId":0,"wgArticleId":20,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Coded_Beacon_Frame","wgRelevantArticleId":20,"wgRequestId":"XcOqnaI8Bos5ze83YO5QOwAAARE","wgCSPNonce":false,"wgIsProbablyEditable":false,"wgRelevantPageIsProbablyEditable":false,"wgRestrictionEdit":[],"wgRestrictionMove":[]});mw.loader.state({"site.styles":"ready","noscript":"ready","user.styles":"ready","user":"ready","user.options":"ready","user.tokens":"loading","mediawiki.interface.helpers.styles":"ready","mediawiki.action.history.styles":"ready","mediawiki.special.changeslist":"ready","mediawiki.helplink":"ready","mediawiki.legacy.shared":"ready","mediawiki.legacy.commonPrint":"ready","mediawiki.feedlink":"ready","mediawiki.skinning.interface":"ready","skins.vector.styles":"ready"});mw.loader.implement("user.tokens@0tffind",function($,jQuery,require,module){/*@nomin*/mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
});RLPAGEMODULES=["mediawiki.action.history","site","mediawiki.page.startup","mediawiki.page.ready","mediawiki.searchSuggest","skins.vector.js"];mw.loader.load(RLPAGEMODULES);});</script>
<link rel="stylesheet" href="loadcaad.css?lang=en&amp;modules=mediawiki.action.history.styles%7Cmediawiki.feedlink%2Chelplink%7Cmediawiki.interface.helpers.styles%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.interface%7Cmediawiki.special.changeslist%7Cskins.vector.styles&amp;only=styles&amp;skin=vector"/>
<script async="" src="load3e21.php?lang=en&amp;modules=startup&amp;only=scripts&amp;skin=vector"></script>
<meta name="ResourceLoaderDynamicStyles" content=""/>
<link rel="stylesheet" href="load2f5e.css?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector"/>
<meta name="generator" content="MediaWiki 1.33.0"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="shortcut icon" href="http://subpos.org/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="http://subpos.org/wiki/opensearch_desc.php" title="SubPos (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://subpos.org/wiki/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;Coded Beacon Frame&quot; Atom feed" href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="SubPos Atom feed" href="http://subpos.org/wiki/index.php?title=Special:RecentChanges&amp;feed=atom"/>
<!--[if lt IE 9]><script src="/wiki/load.php?lang=en&amp;modules=html5shiv&amp;only=scripts&amp;skin=vector&amp;sync=1"></script><![endif]-->
</head>
<body class="mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject page-Coded_Beacon_Frame rootpage-Coded_Beacon_Frame skin-vector action-history">
<div id="mw-page-base" class="noprint"></div>
<div id="mw-head-base" class="noprint"></div>
<div id="content" class="mw-body" role="main">
	<a id="top"></a>
	
	<div class="mw-indicators mw-body-content">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="http://meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>

	<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "Coded Beacon Frame"</h1>
	
	<div id="bodyContent" class="mw-body-content">
		
		<div id="contentSub"><div class="mw-history-subtitle"><a href="http://subpos.org/wiki/index.php?title=Special:Log&amp;page=Coded+Beacon+Frame" title="Special:Log">View logs for this page</a></div></div>
		
		
		
		<div id="jump-to-nav"></div>
		<a class="mw-jump-link" href="#mw-head">Jump to navigation</a>
		<a class="mw-jump-link" href="#p-search">Jump to search</a>
		<div id="mw-content-text"><form action="http://subpos.org/wiki/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Search for revisions</legend>
<input type="hidden" value="Coded_Beacon_Frame" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2019" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select> <label for="tagfilter"><a href="http://subpos.org/wiki/index.php/Special:Tags" title="Special:Tags">Tag</a> filter:</label> <input name="tagfilter" size="20" value="" class="mw-tagfilter-input mw-ui-input mw-ui-input-inline" id="tagfilter" /> <input type="submit" value="Show revisions"/>
</fieldset>
</form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div>(newest | <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;dir=prev&amp;action=history" class="mw-lastlink" title="Coded Beacon Frame">oldest</a>) View (newer 50  |  <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;offset=20150507115655&amp;action=history" class="mw-nextlink" title="Coded Beacon Frame" rel="next">older 50</a>) (<a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;offset=&amp;limit=20&amp;action=history" class="mw-numlink" title="Coded Beacon Frame">20</a> | <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;offset=&amp;limit=50&amp;action=history" class="mw-numlink" title="Coded Beacon Frame">50</a> | <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;offset=&amp;limit=100&amp;action=history" class="mw-numlink" title="Coded Beacon Frame">100</a> | <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;offset=&amp;limit=250&amp;action=history" class="mw-numlink" title="Coded Beacon Frame">250</a> | <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;offset=&amp;limit=500&amp;action=history" class="mw-numlink" title="Coded Beacon Frame">500</a>)<form action="http://subpos.org/wiki/index.php" id="mw-history-compare">
<input type="hidden" value="Coded_Beacon_Frame" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div class="mw-history-compareselectedversions"><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li data-mw-revid="516"><span class="mw-history-histlinks mw-changeslist-links"><span>cur</span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=515" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="516" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="516" checked="checked" name="diff" id="mw-diff-516" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=516" class="mw-changeslist-date" title="Coded Beacon Frame">02:27, 21 April 2017</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,906 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,906 bytes after change">+69</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses"><span dir="auto"><span class="autocomment"><a href="http://subpos.org/wiki/index.php/Coded_Beacon_Frame#Notes" title="Coded Beacon Frame">→‎Notes</a></span></span></span></li>
<li data-mw-revid="515"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=515" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=515&amp;oldid=514" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="515" checked="checked" name="oldid" id="mw-oldid-515" /><input type="radio" value="515" name="diff" id="mw-diff-515" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=515" class="mw-changeslist-date" title="Coded Beacon Frame">02:26, 21 April 2017</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,837 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,837 bytes after change">+22</span>‎</li>
<li data-mw-revid="514"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=514" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=514&amp;oldid=513" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="514" name="oldid" id="mw-oldid-514" /><input type="radio" value="514" name="diff" id="mw-diff-514" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=514" class="mw-changeslist-date" title="Coded Beacon Frame">02:25, 21 April 2017</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,815 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,815 bytes after change">+4</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses"><span dir="auto"><span class="autocomment"><a href="http://subpos.org/wiki/index.php/Coded_Beacon_Frame#Notes" title="Coded Beacon Frame">→‎Notes</a></span></span></span></li>
<li data-mw-revid="513"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=513" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=513&amp;oldid=512" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="513" name="oldid" id="mw-oldid-513" /><input type="radio" value="513" name="diff" id="mw-diff-513" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=513" class="mw-changeslist-date" title="Coded Beacon Frame">02:25, 21 April 2017</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,811 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,811 bytes after change">+37</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses"><span dir="auto"><span class="autocomment"><a href="http://subpos.org/wiki/index.php/Coded_Beacon_Frame#Notes" title="Coded Beacon Frame">→‎Notes</a></span></span></span></li>
<li data-mw-revid="512"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=512" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=512&amp;oldid=511" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="512" name="oldid" id="mw-oldid-512" /><input type="radio" value="512" name="diff" id="mw-diff-512" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=512" class="mw-changeslist-date" title="Coded Beacon Frame">02:24, 21 April 2017</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,774 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,774 bytes after change">+41</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses"><span dir="auto"><span class="autocomment"><a href="http://subpos.org/wiki/index.php/Coded_Beacon_Frame#Notes" title="Coded Beacon Frame">→‎Notes</a></span></span></span></li>
<li data-mw-revid="511"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=511" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=511&amp;oldid=510" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="511" name="oldid" id="mw-oldid-511" /><input type="radio" value="511" name="diff" id="mw-diff-511" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=511" class="mw-changeslist-date" title="Coded Beacon Frame">02:23, 21 April 2017</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,733 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,733 bytes after change">+52</span>‎</li>
<li data-mw-revid="510"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=510" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=510&amp;oldid=509" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="510" name="oldid" id="mw-oldid-510" /><input type="radio" value="510" name="diff" id="mw-diff-510" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=510" class="mw-changeslist-date" title="Coded Beacon Frame">02:22, 21 April 2017</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,681 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,681 bytes after change">+14</span>‎</li>
<li data-mw-revid="509"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=509" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=509&amp;oldid=508" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="509" name="oldid" id="mw-oldid-509" /><input type="radio" value="509" name="diff" id="mw-diff-509" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=509" class="mw-changeslist-date" title="Coded Beacon Frame">02:21, 21 April 2017</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,667 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,667 bytes after change">+8</span>‎</li>
<li data-mw-revid="508"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=508" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=508&amp;oldid=507" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="508" name="oldid" id="mw-oldid-508" /><input type="radio" value="508" name="diff" id="mw-diff-508" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=508" class="mw-changeslist-date" title="Coded Beacon Frame">02:20, 21 April 2017</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,659 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="3,659 bytes after change">-8</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses"><span dir="auto"><span class="autocomment"><a href="http://subpos.org/wiki/index.php/Coded_Beacon_Frame#Implementation" title="Coded Beacon Frame">→‎Implementation</a></span></span></span></li>
<li data-mw-revid="507"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=507" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=507&amp;oldid=506" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="507" name="oldid" id="mw-oldid-507" /><input type="radio" value="507" name="diff" id="mw-diff-507" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=507" class="mw-changeslist-date" title="Coded Beacon Frame">02:17, 21 April 2017</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,667 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,667 bytes after change">+28</span>‎</li>
<li data-mw-revid="506"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=506" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=506&amp;oldid=505" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="506" name="oldid" id="mw-oldid-506" /><input type="radio" value="506" name="diff" id="mw-diff-506" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=506" class="mw-changeslist-date" title="Coded Beacon Frame">02:16, 21 April 2017</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,639 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,639 bytes after change">+170</span>‎</li>
<li data-mw-revid="505"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=505" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=505&amp;oldid=504" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="505" name="oldid" id="mw-oldid-505" /><input type="radio" value="505" name="diff" id="mw-diff-505" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=505" class="mw-changeslist-date" title="Coded Beacon Frame">02:04, 21 April 2017</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,469 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,469 bytes after change">+32</span>‎</li>
<li data-mw-revid="504"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=504" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=504&amp;oldid=503" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="504" name="oldid" id="mw-oldid-504" /><input type="radio" value="504" name="diff" id="mw-diff-504" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=504" class="mw-changeslist-date" title="Coded Beacon Frame">02:02, 21 April 2017</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,437 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,437 bytes after change">+322</span>‎</li>
<li data-mw-revid="503"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=503" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=503&amp;oldid=501" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="503" name="oldid" id="mw-oldid-503" /><input type="radio" value="503" name="diff" id="mw-diff-503" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=503" class="mw-changeslist-date" title="Coded Beacon Frame">02:00, 21 April 2017</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,115 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,115 bytes after change">+13</span>‎</li>
<li data-mw-revid="501"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=501" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=501&amp;oldid=500" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="501" name="oldid" id="mw-oldid-501" /><input type="radio" value="501" name="diff" id="mw-diff-501" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=501" class="mw-changeslist-date" title="Coded Beacon Frame">01:51, 21 April 2017</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,102 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,102 bytes after change">+26</span>‎</li>
<li data-mw-revid="500"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=500" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=500&amp;oldid=499" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="500" name="oldid" id="mw-oldid-500" /><input type="radio" value="500" name="diff" id="mw-diff-500" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=500" class="mw-changeslist-date" title="Coded Beacon Frame">01:50, 21 April 2017</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,076 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,076 bytes after change">+9</span>‎</li>
<li data-mw-revid="499"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=499" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=499&amp;oldid=498" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="499" name="oldid" id="mw-oldid-499" /><input type="radio" value="499" name="diff" id="mw-diff-499" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=499" class="mw-changeslist-date" title="Coded Beacon Frame">01:50, 21 April 2017</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,067 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,067 bytes after change">+24</span>‎</li>
<li data-mw-revid="498"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=498" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=498&amp;oldid=497" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="498" name="oldid" id="mw-oldid-498" /><input type="radio" value="498" name="diff" id="mw-diff-498" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=498" class="mw-changeslist-date" title="Coded Beacon Frame">01:49, 21 April 2017</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,043 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,043 bytes after change">+158</span>‎</li>
<li data-mw-revid="497"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=497" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=497&amp;oldid=496" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="497" name="oldid" id="mw-oldid-497" /><input type="radio" value="497" name="diff" id="mw-diff-497" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=497" class="mw-changeslist-date" title="Coded Beacon Frame">01:47, 21 April 2017</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,885 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,885 bytes after change">+46</span>‎</li>
<li data-mw-revid="496"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=496" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=496&amp;oldid=492" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="496" name="oldid" id="mw-oldid-496" /><input type="radio" value="496" name="diff" id="mw-diff-496" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=496" class="mw-changeslist-date" title="Coded Beacon Frame">01:45, 21 April 2017</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,839 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,839 bytes after change">+29</span>‎</li>
<li data-mw-revid="492"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=492" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=492&amp;oldid=491" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="492" name="oldid" id="mw-oldid-492" /><input type="radio" value="492" name="diff" id="mw-diff-492" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=492" class="mw-changeslist-date" title="Coded Beacon Frame">01:04, 21 April 2017</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,810 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,810 bytes after change">+85</span>‎</li>
<li data-mw-revid="491"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=491" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=491&amp;oldid=359" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="491" name="oldid" id="mw-oldid-491" /><input type="radio" value="491" name="diff" id="mw-diff-491" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=491" class="mw-changeslist-date" title="Coded Beacon Frame">01:03, 21 April 2017</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,725 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,725 bytes after change">+84</span>‎</li>
<li data-mw-revid="359"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=359" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=359&amp;oldid=349" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="359" name="oldid" id="mw-oldid-359" /><input type="radio" value="359" name="diff" id="mw-diff-359" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=359" class="mw-changeslist-date" title="Coded Beacon Frame">02:26, 26 October 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,641 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,641 bytes after change">+105</span>‎</li>
<li data-mw-revid="349"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=349" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=349&amp;oldid=348" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="349" name="oldid" id="mw-oldid-349" /><input type="radio" value="349" name="diff" id="mw-diff-349" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=349" class="mw-changeslist-date" title="Coded Beacon Frame">21:38, 26 September 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,536 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,536 bytes after change">+101</span>‎</li>
<li data-mw-revid="348"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=348" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=348&amp;oldid=347" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="348" name="oldid" id="mw-oldid-348" /><input type="radio" value="348" name="diff" id="mw-diff-348" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=348" class="mw-changeslist-date" title="Coded Beacon Frame">20:50, 26 September 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,435 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="2,435 bytes after change">-2</span>‎</li>
<li data-mw-revid="347"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=347" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=347&amp;oldid=346" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="347" name="oldid" id="mw-oldid-347" /><input type="radio" value="347" name="diff" id="mw-diff-347" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=347" class="mw-changeslist-date" title="Coded Beacon Frame">20:49, 26 September 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,437 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,437 bytes after change">+57</span>‎</li>
<li data-mw-revid="346"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=346" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=346&amp;oldid=345" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="346" name="oldid" id="mw-oldid-346" /><input type="radio" value="346" name="diff" id="mw-diff-346" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=346" class="mw-changeslist-date" title="Coded Beacon Frame">20:48, 26 September 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,380 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,380 bytes after change">+11</span>‎</li>
<li data-mw-revid="345"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=345" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=345&amp;oldid=344" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="345" name="oldid" id="mw-oldid-345" /><input type="radio" value="345" name="diff" id="mw-diff-345" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=345" class="mw-changeslist-date" title="Coded Beacon Frame">20:48, 26 September 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,369 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,369 bytes after change">+2</span>‎</li>
<li data-mw-revid="344"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=344" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=344&amp;oldid=343" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="344" name="oldid" id="mw-oldid-344" /><input type="radio" value="344" name="diff" id="mw-diff-344" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=344" class="mw-changeslist-date" title="Coded Beacon Frame">20:47, 26 September 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,367 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="2,367 bytes after change">-3</span>‎</li>
<li data-mw-revid="343"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=343" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=343&amp;oldid=303" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="343" name="oldid" id="mw-oldid-343" /><input type="radio" value="343" name="diff" id="mw-diff-343" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=343" class="mw-changeslist-date" title="Coded Beacon Frame">20:46, 26 September 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,370 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,370 bytes after change">+380</span>‎</li>
<li data-mw-revid="303"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=303" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=303&amp;oldid=283" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="303" name="oldid" id="mw-oldid-303" /><input type="radio" value="303" name="diff" id="mw-diff-303" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=303" class="mw-changeslist-date" title="Coded Beacon Frame">03:43, 17 August 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,990 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,990 bytes after change">+20</span>‎</li>
<li data-mw-revid="283"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=283" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=283&amp;oldid=281" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="283" name="oldid" id="mw-oldid-283" /><input type="radio" value="283" name="diff" id="mw-diff-283" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=283" class="mw-changeslist-date" title="Coded Beacon Frame">22:40, 21 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,970 bytes</span> <span dir="ltr" class="mw-plusminus-null mw-diff-bytes" title="1,970 bytes after change">0</span>‎</li>
<li data-mw-revid="281"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=281" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=281&amp;oldid=229" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="281" name="oldid" id="mw-oldid-281" /><input type="radio" value="281" name="diff" id="mw-diff-281" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=281" class="mw-changeslist-date" title="Coded Beacon Frame">22:37, 21 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,970 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,970 bytes after change">+260</span>‎</li>
<li data-mw-revid="229"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=229" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=229&amp;oldid=228" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="229" name="oldid" id="mw-oldid-229" /><input type="radio" value="229" name="diff" id="mw-diff-229" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=229" class="mw-changeslist-date" title="Coded Beacon Frame">02:25, 15 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,710 bytes</span> <span dir="ltr" class="mw-plusminus-null mw-diff-bytes" title="1,710 bytes after change">0</span>‎</li>
<li data-mw-revid="228"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=228" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=228&amp;oldid=219" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="228" name="oldid" id="mw-oldid-228" /><input type="radio" value="228" name="diff" id="mw-diff-228" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=228" class="mw-changeslist-date" title="Coded Beacon Frame">02:18, 15 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,710 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,710 bytes after change">+113</span>‎</li>
<li data-mw-revid="219"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=219" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=219&amp;oldid=218" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="219" name="oldid" id="mw-oldid-219" /><input type="radio" value="219" name="diff" id="mw-diff-219" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=219" class="mw-changeslist-date" title="Coded Beacon Frame">02:58, 14 June 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,597 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="1,597 bytes after change">-32</span>‎</li>
<li data-mw-revid="218"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=218" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=218&amp;oldid=217" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="218" name="oldid" id="mw-oldid-218" /><input type="radio" value="218" name="diff" id="mw-diff-218" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=218" class="mw-changeslist-date" title="Coded Beacon Frame">22:58, 13 June 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,629 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="1,629 bytes after change">-7</span>‎</li>
<li data-mw-revid="217"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=217" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=217&amp;oldid=216" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="217" name="oldid" id="mw-oldid-217" /><input type="radio" value="217" name="diff" id="mw-diff-217" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=217" class="mw-changeslist-date" title="Coded Beacon Frame">22:40, 13 June 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,636 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="1,636 bytes after change">-2</span>‎</li>
<li data-mw-revid="216"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=216" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=216&amp;oldid=215" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="216" name="oldid" id="mw-oldid-216" /><input type="radio" value="216" name="diff" id="mw-diff-216" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=216" class="mw-changeslist-date" title="Coded Beacon Frame">22:39, 13 June 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,638 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,638 bytes after change">+15</span>‎</li>
<li data-mw-revid="215"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=215" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=215&amp;oldid=168" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="215" name="oldid" id="mw-oldid-215" /><input type="radio" value="215" name="diff" id="mw-diff-215" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=215" class="mw-changeslist-date" title="Coded Beacon Frame">22:08, 13 June 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,623 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,623 bytes after change">+55</span>‎</li>
<li data-mw-revid="168"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=168" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=168&amp;oldid=167" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="168" name="oldid" id="mw-oldid-168" /><input type="radio" value="168" name="diff" id="mw-diff-168" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=168" class="mw-changeslist-date" title="Coded Beacon Frame">04:27, 19 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,568 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,568 bytes after change">+9</span>‎</li>
<li data-mw-revid="167"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=167" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=167&amp;oldid=164" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="167" name="oldid" id="mw-oldid-167" /><input type="radio" value="167" name="diff" id="mw-diff-167" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=167" class="mw-changeslist-date" title="Coded Beacon Frame">04:26, 19 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,559 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,559 bytes after change">+144</span>‎</li>
<li data-mw-revid="164"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=164" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=164&amp;oldid=122" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="164" name="oldid" id="mw-oldid-164" /><input type="radio" value="164" name="diff" id="mw-diff-164" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=164" class="mw-changeslist-date" title="Coded Beacon Frame">06:44, 17 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,415 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,415 bytes after change">+72</span>‎</li>
<li data-mw-revid="122"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=122" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=122&amp;oldid=121" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="122" name="oldid" id="mw-oldid-122" /><input type="radio" value="122" name="diff" id="mw-diff-122" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=122" class="mw-changeslist-date" title="Coded Beacon Frame">10:56, 8 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,343 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="1,343 bytes after change">-168</span>‎</li>
<li data-mw-revid="121"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=121" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=121&amp;oldid=120" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="121" name="oldid" id="mw-oldid-121" /><input type="radio" value="121" name="diff" id="mw-diff-121" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=121" class="mw-changeslist-date" title="Coded Beacon Frame">10:39, 8 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,511 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,511 bytes after change">+8</span>‎</li>
<li data-mw-revid="120"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=120" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=120&amp;oldid=100" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="120" name="oldid" id="mw-oldid-120" /><input type="radio" value="120" name="diff" id="mw-diff-120" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=120" class="mw-changeslist-date" title="Coded Beacon Frame">07:35, 8 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,503 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,503 bytes after change">+160</span>‎</li>
<li data-mw-revid="100"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=100" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=100&amp;oldid=86" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="100" name="oldid" id="mw-oldid-100" /><input type="radio" value="100" name="diff" id="mw-diff-100" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=100" class="mw-changeslist-date" title="Coded Beacon Frame">08:03, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,343 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="1,343 bytes after change">-22</span>‎</li>
<li data-mw-revid="86"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=86" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=86&amp;oldid=85" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="86" name="oldid" id="mw-oldid-86" /><input type="radio" value="86" name="diff" id="mw-diff-86" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=86" class="mw-changeslist-date" title="Coded Beacon Frame">07:36, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,365 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,365 bytes after change">+1</span>‎</li>
<li data-mw-revid="85"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=85" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=85&amp;oldid=59" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="85" name="oldid" id="mw-oldid-85" /><input type="radio" value="85" name="diff" id="mw-diff-85" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=85" class="mw-changeslist-date" title="Coded Beacon Frame">07:36, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,364 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,364 bytes after change">+170</span>‎</li>
<li data-mw-revid="59"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=516&amp;oldid=59" title="Coded Beacon Frame">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;diff=59&amp;oldid=58" title="Coded Beacon Frame">prev</a></span></span><input type="radio" value="59" name="oldid" id="mw-oldid-59" /><input type="radio" value="59" name="diff" id="mw-diff-59" /> <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;oldid=59" class="mw-changeslist-date" title="Coded Beacon Frame">06:56, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,194 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,194 bytes after change">+481</span>‎</li>
</ul>
<div class="mw-history-compareselectedversions"><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form>(newest | <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;dir=prev&amp;action=history" class="mw-lastlink" title="Coded Beacon Frame">oldest</a>) View (newer 50  |  <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;offset=20150507115655&amp;action=history" class="mw-nextlink" title="Coded Beacon Frame" rel="next">older 50</a>) (<a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;offset=&amp;limit=20&amp;action=history" class="mw-numlink" title="Coded Beacon Frame">20</a> | <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;offset=&amp;limit=50&amp;action=history" class="mw-numlink" title="Coded Beacon Frame">50</a> | <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;offset=&amp;limit=100&amp;action=history" class="mw-numlink" title="Coded Beacon Frame">100</a> | <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;offset=&amp;limit=250&amp;action=history" class="mw-numlink" title="Coded Beacon Frame">250</a> | <a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;offset=&amp;limit=500&amp;action=history" class="mw-numlink" title="Coded Beacon Frame">500</a>)</div>
		
		<div class="printfooter">Retrieved from "<a dir="ltr" href="http://subpos.org/wiki/index.php/Coded_Beacon_Frame">http://subpos.org/wiki/index.php/Coded_Beacon_Frame</a>"</div>
		
		<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>
		
		<div class="visualClear"></div>
		
	</div>
</div>

		<div id="mw-navigation">
			<h2>Navigation menu</h2>
			<div id="mw-head">
									<div id="p-personal" role="navigation" aria-labelledby="p-personal-label">
						<h3 id="p-personal-label">Personal tools</h3>
						<ul>
							<li id="pt-login"><a href="http://subpos.org/wiki/index.php?title=Special:UserLogin&amp;returnto=Coded+Beacon+Frame&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>						</ul>
					</div>
									<div id="left-navigation">
										<div id="p-namespaces" role="navigation" class="vectorTabs" aria-labelledby="p-namespaces-label">
						<h3 id="p-namespaces-label">Namespaces</h3>
						<ul>
							<li id="ca-nstab-main" class="selected"><span><a href="http://subpos.org/wiki/index.php/Coded_Beacon_Frame" title="View the content page [c]" accesskey="c">Page</a></span></li><li id="ca-talk" class="new"><span><a href="http://subpos.org/wiki/index.php?title=Talk:Coded_Beacon_Frame&amp;action=edit&amp;redlink=1" rel="discussion" title="Discussion about the content page (page does not exist) [t]" accesskey="t">Discussion</a></span></li>						</ul>
					</div>
										<div id="p-variants" role="navigation" class="vectorMenu emptyPortlet" aria-labelledby="p-variants-label">
												<input type="checkbox" class="vectorMenuCheckbox" aria-labelledby="p-variants-label" />
						<h3 id="p-variants-label">
							<span>Variants</span>
						</h3>
						<ul class="menu">
													</ul>
					</div>
									</div>
				<div id="right-navigation">
										<div id="p-views" role="navigation" class="vectorTabs" aria-labelledby="p-views-label">
						<h3 id="p-views-label">Views</h3>
						<ul>
							<li id="ca-view" class="collapsible"><span><a href="http://subpos.org/wiki/index.php/Coded_Beacon_Frame">Read</a></span></li><li id="ca-viewsource" class="collapsible"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;action=edit" title="This page is protected.&#10;You can view its source [e]" accesskey="e">View source</a></span></li><li id="ca-history" class="collapsible selected"><span><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;action=history" title="Past revisions of this page [h]" accesskey="h">View history</a></span></li>						</ul>
					</div>
										<div id="p-cactions" role="navigation" class="vectorMenu emptyPortlet" aria-labelledby="p-cactions-label">
						<input type="checkbox" class="vectorMenuCheckbox" aria-labelledby="p-cactions-label" />
						<h3 id="p-cactions-label"><span>More</span></h3>
						<ul class="menu">
													</ul>
					</div>
										<div id="p-search" role="search">
						<h3>
							<label for="searchInput">Search</label>
						</h3>
						<form action="http://subpos.org/wiki/index.php" id="searchform">
							<div id="simpleSearch">
								<input type="search" name="search" placeholder="Search SubPos" title="Search SubPos [f]" accesskey="f" id="searchInput"/><input type="hidden" value="Special:Search" name="title"/><input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton mw-fallbackSearchButton"/><input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchButton" class="searchButton"/>							</div>
						</form>
					</div>
									</div>
			</div>
			<div id="mw-panel">
				<div id="p-logo" role="banner"><a class="mw-wiki-logo" href="http://subpos.org/wiki/index.php/SubPos" title="Visit the main page"></a></div>
						<div class="portal" role="navigation" id="p-navigation" aria-labelledby="p-navigation-label">
			<h3 id="p-navigation-label">Navigation</h3>
			<div class="body">
								<ul>
					<li id="n-mainpage-description"><a href="http://subpos.org/wiki/index.php/SubPos" title="Visit the main page [z]" accesskey="z">Main page</a></li><li id="n-Documentation"><a href="http://subpos.org/wiki/index.php/SubPos:Documentation">Documentation</a></li><li id="n-Software"><a href="http://subpos.org/wiki/index.php/SubPos:Software">Software</a></li><li id="n-Hardware"><a href="http://subpos.org/wiki/index.php/SubPos:Hardware">Hardware</a></li><li id="n-Repository"><a href="http://subpos.org/wiki/index.php/SubPos:Repository">Repository</a></li><li id="n-Main-site"><a href="https://www.subpos.org/" rel="nofollow">Main site</a></li>				</ul>
							</div>
		</div>
			<div class="portal" role="navigation" id="p-tb" aria-labelledby="p-tb-label">
			<h3 id="p-tb-label">Tools</h3>
			<div class="body">
								<ul>
					<li id="t-whatlinkshere"><a href="http://subpos.org/wiki/index.php/Special:WhatLinksHere/Coded_Beacon_Frame" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li><li id="t-recentchangeslinked"><a href="http://subpos.org/wiki/index.php/Special:RecentChangesLinked/Coded_Beacon_Frame" rel="nofollow" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li><li id="feedlinks"><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li><li id="t-specialpages"><a href="http://subpos.org/wiki/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li><li id="t-info"><a href="http://subpos.org/wiki/index.php?title=Coded_Beacon_Frame&amp;action=info" title="More information about this page">Page information</a></li>				</ul>
							</div>
		</div>
				</div>
		</div>
				<div id="footer" role="contentinfo">
						<ul id="footer-places">
								<li id="footer-places-privacy"><a href="http://subpos.org/wiki/index.php/SubPos:Privacy_policy" title="SubPos:Privacy policy">Privacy policy</a></li>
								<li id="footer-places-about"><a href="http://subpos.org/wiki/index.php/SubPos:About" title="SubPos:About">About SubPos</a></li>
								<li id="footer-places-disclaimer"><a href="http://subpos.org/wiki/index.php/SubPos:General_disclaimer" title="SubPos:General disclaimer">Disclaimers</a></li>
							</ul>
									<div style="clear: both;"></div>
		</div>
		

<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":180});});</script>
</body>

<!-- Mirrored from subpos.org/wiki/index.php?title=Coded_Beacon_Frame&action=history by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 07 Nov 2019 05:39:18 GMT -->
</html>
