<!DOCTYPE html>
<html class="client-nojs" lang="en" dir="ltr">

<!-- Mirrored from subpos.org/wiki/index.php?title=SubPos&action=history by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 07 Nov 2019 05:39:08 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
<head>
<meta charset="UTF-8"/>
<title>Revision history of "SubPos" - SubPos</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"SubPos","wgTitle":"SubPos","wgCurRevisionId":463,"wgRevisionId":0,"wgArticleId":1,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"SubPos","wgRelevantArticleId":1,"wgRequestId":"XcOp-dqMYI0sdTvAfUZiHQAAAJI","wgCSPNonce":false,"wgIsProbablyEditable":false,"wgRelevantPageIsProbablyEditable":false,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgIsMainPage":true});mw.loader.state({"site.styles":"ready","noscript":"ready","user.styles":"ready","user":"ready","user.options":"ready","user.tokens":"loading","mediawiki.interface.helpers.styles":"ready","mediawiki.action.history.styles":"ready","mediawiki.special.changeslist":"ready","mediawiki.helplink":"ready","mediawiki.legacy.shared":"ready","mediawiki.legacy.commonPrint":"ready","mediawiki.feedlink":"ready","mediawiki.skinning.interface":"ready","skins.vector.styles":"ready"});mw.loader.implement("user.tokens@0tffind",function($,jQuery,require,module){/*@nomin*/mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
});RLPAGEMODULES=["mediawiki.action.history","site","mediawiki.page.startup","mediawiki.page.ready","mediawiki.searchSuggest","skins.vector.js"];mw.loader.load(RLPAGEMODULES);});</script>
<link rel="stylesheet" href="loadcaad.css?lang=en&amp;modules=mediawiki.action.history.styles%7Cmediawiki.feedlink%2Chelplink%7Cmediawiki.interface.helpers.styles%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.interface%7Cmediawiki.special.changeslist%7Cskins.vector.styles&amp;only=styles&amp;skin=vector"/>
<script async="" src="load3e21.php?lang=en&amp;modules=startup&amp;only=scripts&amp;skin=vector"></script>
<meta name="ResourceLoaderDynamicStyles" content=""/>
<link rel="stylesheet" href="load2f5e.css?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector"/>
<meta name="generator" content="MediaWiki 1.33.0"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="shortcut icon" href="http://subpos.org/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="http://subpos.org/wiki/opensearch_desc.php" title="SubPos (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://subpos.org/wiki/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;SubPos&quot; Atom feed" href="http://subpos.org/wiki/index.php?title=SubPos&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="SubPos Atom feed" href="http://subpos.org/wiki/index.php?title=Special:RecentChanges&amp;feed=atom"/>
<!--[if lt IE 9]><script src="/wiki/load.php?lang=en&amp;modules=html5shiv&amp;only=scripts&amp;skin=vector&amp;sync=1"></script><![endif]-->
</head>
<body class="mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject page-SubPos rootpage-SubPos skin-vector action-history">
<div id="mw-page-base" class="noprint"></div>
<div id="mw-head-base" class="noprint"></div>
<div id="content" class="mw-body" role="main">
	<a id="top"></a>
	
	<div class="mw-indicators mw-body-content">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="http://meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>

	<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "SubPos"</h1>
	
	<div id="bodyContent" class="mw-body-content">
		
		<div id="contentSub"><div class="mw-history-subtitle"><a href="http://subpos.org/wiki/index.php?title=Special:Log&amp;page=SubPos" title="Special:Log">View logs for this page</a></div></div>
		
		
		
		<div id="jump-to-nav"></div>
		<a class="mw-jump-link" href="#mw-head">Jump to navigation</a>
		<a class="mw-jump-link" href="#p-search">Jump to search</a>
		<div id="mw-content-text"><form action="http://subpos.org/wiki/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Search for revisions</legend>
<input type="hidden" value="SubPos" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2019" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select> <label for="tagfilter"><a href="http://subpos.org/wiki/index.php/Special:Tags" title="Special:Tags">Tag</a> filter:</label> <input name="tagfilter" size="20" value="" class="mw-tagfilter-input mw-ui-input mw-ui-input-inline" id="tagfilter" /> <input type="submit" value="Show revisions"/>
</fieldset>
</form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div><form action="http://subpos.org/wiki/index.php" id="mw-history-compare">
<input type="hidden" value="SubPos" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div class="mw-history-compareselectedversions"><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li data-mw-revid="463"><span class="mw-history-histlinks mw-changeslist-links"><span>cur</span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=462" title="SubPos">prev</a></span></span><input type="radio" value="463" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="463" checked="checked" name="diff" id="mw-diff-463" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=463" class="mw-changeslist-date" title="SubPos">07:02, 4 July 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,027 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="2,027 bytes after change">-7</span>‎</li>
<li data-mw-revid="462"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=462" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=462&amp;oldid=461" title="SubPos">prev</a></span></span><input type="radio" value="462" checked="checked" name="oldid" id="mw-oldid-462" /><input type="radio" value="462" name="diff" id="mw-diff-462" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=462" class="mw-changeslist-date" title="SubPos">07:01, 4 July 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,034 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="2,034 bytes after change">-12</span>‎</li>
<li data-mw-revid="461"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=461" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=461&amp;oldid=460" title="SubPos">prev</a></span></span><input type="radio" value="461" name="oldid" id="mw-oldid-461" /><input type="radio" value="461" name="diff" id="mw-diff-461" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=461" class="mw-changeslist-date" title="SubPos">06:58, 4 July 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,046 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="2,046 bytes after change">-43</span>‎</li>
<li data-mw-revid="460"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=460" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=460&amp;oldid=397" title="SubPos">prev</a></span></span><input type="radio" value="460" name="oldid" id="mw-oldid-460" /><input type="radio" value="460" name="diff" id="mw-diff-460" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=460" class="mw-changeslist-date" title="SubPos">06:57, 4 July 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,089 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,089 bytes after change">+62</span>‎</li>
<li data-mw-revid="397"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=397" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=397&amp;oldid=360" title="SubPos">prev</a></span></span><input type="radio" value="397" name="oldid" id="mw-oldid-397" /><input type="radio" value="397" name="diff" id="mw-diff-397" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=397" class="mw-changeslist-date" title="SubPos">22:18, 6 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,027 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="2,027 bytes after change">-116</span>‎</li>
<li data-mw-revid="360"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=360" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=360&amp;oldid=336" title="SubPos">prev</a></span></span><input type="radio" value="360" name="oldid" id="mw-oldid-360" /><input type="radio" value="360" name="diff" id="mw-diff-360" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=360" class="mw-changeslist-date" title="SubPos">00:40, 21 November 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,143 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="2,143 bytes after change">-292</span>‎</li>
<li data-mw-revid="336"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=336" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=336&amp;oldid=335" title="SubPos">prev</a></span></span><input type="radio" value="336" name="oldid" id="mw-oldid-336" /><input type="radio" value="336" name="diff" id="mw-diff-336" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=336" class="mw-changeslist-date" title="SubPos">20:54, 21 September 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,435 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,435 bytes after change">+68</span>‎</li>
<li data-mw-revid="335"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=335" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=335&amp;oldid=334" title="SubPos">prev</a></span></span><input type="radio" value="335" name="oldid" id="mw-oldid-335" /><input type="radio" value="335" name="diff" id="mw-diff-335" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=335" class="mw-changeslist-date" title="SubPos">23:57, 13 September 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,367 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,367 bytes after change">+44</span>‎</li>
<li data-mw-revid="334"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=334" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=334&amp;oldid=333" title="SubPos">prev</a></span></span><input type="radio" value="334" name="oldid" id="mw-oldid-334" /><input type="radio" value="334" name="diff" id="mw-diff-334" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=334" class="mw-changeslist-date" title="SubPos">23:50, 13 September 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,323 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,323 bytes after change">+130</span>‎</li>
<li data-mw-revid="333"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=333" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=333&amp;oldid=327" title="SubPos">prev</a></span></span><input type="radio" value="333" name="oldid" id="mw-oldid-333" /><input type="radio" value="333" name="diff" id="mw-diff-333" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=333" class="mw-changeslist-date" title="SubPos">23:48, 13 September 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,193 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,193 bytes after change">+90</span>‎</li>
<li data-mw-revid="327"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=327" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=327&amp;oldid=326" title="SubPos">prev</a></span></span><input type="radio" value="327" name="oldid" id="mw-oldid-327" /><input type="radio" value="327" name="diff" id="mw-diff-327" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=327" class="mw-changeslist-date" title="SubPos">21:12, 7 September 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,103 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,103 bytes after change">+1</span>‎</li>
<li data-mw-revid="326"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=326" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=326&amp;oldid=279" title="SubPos">prev</a></span></span><input type="radio" value="326" name="oldid" id="mw-oldid-326" /><input type="radio" value="326" name="diff" id="mw-diff-326" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=326" class="mw-changeslist-date" title="SubPos">21:11, 7 September 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,102 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,102 bytes after change">+160</span>‎</li>
<li data-mw-revid="279"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=279" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=279&amp;oldid=277" title="SubPos">prev</a></span></span><input type="radio" value="279" name="oldid" id="mw-oldid-279" /><input type="radio" value="279" name="diff" id="mw-diff-279" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=279" class="mw-changeslist-date" title="SubPos">06:40, 20 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,942 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,942 bytes after change">+36</span>‎</li>
<li data-mw-revid="277"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=277" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=277&amp;oldid=273" title="SubPos">prev</a></span></span><input type="radio" value="277" name="oldid" id="mw-oldid-277" /><input type="radio" value="277" name="diff" id="mw-diff-277" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=277" class="mw-changeslist-date" title="SubPos">06:27, 20 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,906 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,906 bytes after change">+87</span>‎</li>
<li data-mw-revid="273"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=273" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=273&amp;oldid=272" title="SubPos">prev</a></span></span><input type="radio" value="273" name="oldid" id="mw-oldid-273" /><input type="radio" value="273" name="diff" id="mw-diff-273" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=273" class="mw-changeslist-date" title="SubPos">06:09, 20 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,819 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,819 bytes after change">+2</span>‎</li>
<li data-mw-revid="272"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=272" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=272&amp;oldid=271" title="SubPos">prev</a></span></span><input type="radio" value="272" name="oldid" id="mw-oldid-272" /><input type="radio" value="272" name="diff" id="mw-diff-272" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=272" class="mw-changeslist-date" title="SubPos">06:09, 20 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,817 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,817 bytes after change">+10</span>‎</li>
<li data-mw-revid="271"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=271" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=271&amp;oldid=270" title="SubPos">prev</a></span></span><input type="radio" value="271" name="oldid" id="mw-oldid-271" /><input type="radio" value="271" name="diff" id="mw-diff-271" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=271" class="mw-changeslist-date" title="SubPos">06:08, 20 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,807 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,807 bytes after change">+1</span>‎</li>
<li data-mw-revid="270"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=270" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=270&amp;oldid=268" title="SubPos">prev</a></span></span><input type="radio" value="270" name="oldid" id="mw-oldid-270" /><input type="radio" value="270" name="diff" id="mw-diff-270" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=270" class="mw-changeslist-date" title="SubPos">06:05, 20 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,806 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="1,806 bytes after change">-3</span>‎</li>
<li data-mw-revid="268"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=268" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=268&amp;oldid=265" title="SubPos">prev</a></span></span><input type="radio" value="268" name="oldid" id="mw-oldid-268" /><input type="radio" value="268" name="diff" id="mw-diff-268" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=268" class="mw-changeslist-date" title="SubPos">06:03, 20 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,809 bytes</span> <span dir="ltr" class="mw-plusminus-null mw-diff-bytes" title="1,809 bytes after change">0</span>‎</li>
<li data-mw-revid="265"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=265" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=265&amp;oldid=262" title="SubPos">prev</a></span></span><input type="radio" value="265" name="oldid" id="mw-oldid-265" /><input type="radio" value="265" name="diff" id="mw-diff-265" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=265" class="mw-changeslist-date" title="SubPos">06:03, 20 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,809 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,809 bytes after change">+13</span>‎</li>
<li data-mw-revid="262"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=262" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=262&amp;oldid=259" title="SubPos">prev</a></span></span><input type="radio" value="262" name="oldid" id="mw-oldid-262" /><input type="radio" value="262" name="diff" id="mw-diff-262" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=262" class="mw-changeslist-date" title="SubPos">05:59, 20 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,796 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,796 bytes after change">+270</span>‎</li>
<li data-mw-revid="259"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=259" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=259&amp;oldid=258" title="SubPos">prev</a></span></span><input type="radio" value="259" name="oldid" id="mw-oldid-259" /><input type="radio" value="259" name="diff" id="mw-diff-259" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=259" class="mw-changeslist-date" title="SubPos">05:44, 20 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,526 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,526 bytes after change">+13</span>‎</li>
<li data-mw-revid="258"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=258" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=258&amp;oldid=252" title="SubPos">prev</a></span></span><input type="radio" value="258" name="oldid" id="mw-oldid-258" /><input type="radio" value="258" name="diff" id="mw-diff-258" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=258" class="mw-changeslist-date" title="SubPos">05:43, 20 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,513 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,513 bytes after change">+20</span>‎</li>
<li data-mw-revid="252"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=252" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=252&amp;oldid=214" title="SubPos">prev</a></span></span><input type="radio" value="252" name="oldid" id="mw-oldid-252" /><input type="radio" value="252" name="diff" id="mw-diff-252" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=252" class="mw-changeslist-date" title="SubPos">05:33, 20 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,493 bytes</span> <span dir="ltr" class="mw-plusminus-null mw-diff-bytes" title="1,493 bytes after change">0</span>‎</li>
<li data-mw-revid="214"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=214" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=214&amp;oldid=213" title="SubPos">prev</a></span></span><input type="radio" value="214" name="oldid" id="mw-oldid-214" /><input type="radio" value="214" name="diff" id="mw-diff-214" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=214" class="mw-changeslist-date" title="SubPos">01:54, 9 June 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,493 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,493 bytes after change">+104</span>‎</li>
<li data-mw-revid="213"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=213" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=213&amp;oldid=212" title="SubPos">prev</a></span></span><input type="radio" value="213" name="oldid" id="mw-oldid-213" /><input type="radio" value="213" name="diff" id="mw-diff-213" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=213" class="mw-changeslist-date" title="SubPos">01:52, 9 June 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,389 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="1,389 bytes after change">-104</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses">Undo revision 212 by <a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" title="Special:Contributions/Blecky">Blecky</a> (<a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new" title="User talk:Blecky (page does not exist)">talk</a>)</span></li>
<li data-mw-revid="212"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=212" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=212&amp;oldid=178" title="SubPos">prev</a></span></span><input type="radio" value="212" name="oldid" id="mw-oldid-212" /><input type="radio" value="212" name="diff" id="mw-diff-212" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=212" class="mw-changeslist-date" title="SubPos">01:39, 9 June 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,493 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,493 bytes after change">+104</span>‎</li>
<li data-mw-revid="178"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=178" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=178&amp;oldid=177" title="SubPos">prev</a></span></span><input type="radio" value="178" name="oldid" id="mw-oldid-178" /><input type="radio" value="178" name="diff" id="mw-diff-178" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=178" class="mw-changeslist-date" title="SubPos">09:36, 27 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,389 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,389 bytes after change">+132</span>‎</li>
<li data-mw-revid="177"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=177" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=177&amp;oldid=176" title="SubPos">prev</a></span></span><input type="radio" value="177" name="oldid" id="mw-oldid-177" /><input type="radio" value="177" name="diff" id="mw-diff-177" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=177" class="mw-changeslist-date" title="SubPos">09:04, 27 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,257 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,257 bytes after change">+1</span>‎</li>
<li data-mw-revid="176"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=176" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=176&amp;oldid=175" title="SubPos">prev</a></span></span><input type="radio" value="176" name="oldid" id="mw-oldid-176" /><input type="radio" value="176" name="diff" id="mw-diff-176" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=176" class="mw-changeslist-date" title="SubPos">11:53, 26 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,256 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,256 bytes after change">+22</span>‎</li>
<li data-mw-revid="175"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=175" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=175&amp;oldid=174" title="SubPos">prev</a></span></span><input type="radio" value="175" name="oldid" id="mw-oldid-175" /><input type="radio" value="175" name="diff" id="mw-diff-175" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=175" class="mw-changeslist-date" title="SubPos">11:52, 26 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,234 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,234 bytes after change">+1</span>‎</li>
<li data-mw-revid="174"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=174" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=174&amp;oldid=87" title="SubPos">prev</a></span></span><input type="radio" value="174" name="oldid" id="mw-oldid-174" /><input type="radio" value="174" name="diff" id="mw-diff-174" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=174" class="mw-changeslist-date" title="SubPos">11:51, 26 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,233 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,233 bytes after change">+80</span>‎</li>
<li data-mw-revid="87"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=87" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=87&amp;oldid=84" title="SubPos">prev</a></span></span><input type="radio" value="87" name="oldid" id="mw-oldid-87" /><input type="radio" value="87" name="diff" id="mw-diff-87" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=87" class="mw-changeslist-date" title="SubPos">07:37, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,153 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="1,153 bytes after change">-1</span>‎</li>
<li data-mw-revid="84"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=84" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=84&amp;oldid=83" title="SubPos">prev</a></span></span><input type="radio" value="84" name="oldid" id="mw-oldid-84" /><input type="radio" value="84" name="diff" id="mw-diff-84" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=84" class="mw-changeslist-date" title="SubPos">07:33, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,154 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="1,154 bytes after change">-9</span>‎</li>
<li data-mw-revid="83"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=83" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=83&amp;oldid=77" title="SubPos">prev</a></span></span><input type="radio" value="83" name="oldid" id="mw-oldid-83" /><input type="radio" value="83" name="diff" id="mw-diff-83" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=83" class="mw-changeslist-date" title="SubPos">07:32, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,163 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,163 bytes after change">+273</span>‎</li>
<li data-mw-revid="77"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=77" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=77&amp;oldid=29" title="SubPos">prev</a></span></span><input type="radio" value="77" name="oldid" id="mw-oldid-77" /><input type="radio" value="77" name="diff" id="mw-diff-77" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=77" class="mw-changeslist-date" title="SubPos">07:17, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">890 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="890 bytes after change">+6</span>‎</li>
<li data-mw-revid="29"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=29" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=29&amp;oldid=25" title="SubPos">prev</a></span></span><input type="radio" value="29" name="oldid" id="mw-oldid-29" /><input type="radio" value="29" name="diff" id="mw-diff-29" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=29" class="mw-changeslist-date" title="SubPos">05:52, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">884 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="884 bytes after change">+26</span>‎</li>
<li data-mw-revid="25"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=25" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=25&amp;oldid=13" title="SubPos">prev</a></span></span><input type="radio" value="25" name="oldid" id="mw-oldid-25" /><input type="radio" value="25" name="diff" id="mw-diff-25" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=25" class="mw-changeslist-date" title="SubPos">01:07, 6 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">858 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="858 bytes after change">+125</span>‎</li>
<li data-mw-revid="13"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=13" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=13&amp;oldid=12" title="SubPos">prev</a></span></span><input type="radio" value="13" name="oldid" id="mw-oldid-13" /><input type="radio" value="13" name="diff" id="mw-diff-13" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=13" class="mw-changeslist-date" title="SubPos">20:08, 5 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">733 bytes</span> <span dir="ltr" class="mw-plusminus-null mw-diff-bytes" title="733 bytes after change">0</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses">Subpos-WikiSysop moved page <a href="http://subpos.org/wiki/index.php/About_SubPos" class="mw-redirect" title="About SubPos">About SubPos</a> to <a href="http://subpos.org/wiki/index.php/SubPos" title="SubPos">SubPos</a></span></li>
<li data-mw-revid="12"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=12" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=12&amp;oldid=9" title="SubPos">prev</a></span></span><input type="radio" value="12" name="oldid" id="mw-oldid-12" /><input type="radio" value="12" name="diff" id="mw-diff-12" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=12" class="mw-changeslist-date" title="SubPos">20:08, 5 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">733 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="733 bytes after change">+141</span>‎</li>
<li data-mw-revid="9"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=9" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=9&amp;oldid=7" title="SubPos">prev</a></span></span><input type="radio" value="9" name="oldid" id="mw-oldid-9" /><input type="radio" value="9" name="diff" id="mw-diff-9" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=9" class="mw-changeslist-date" title="SubPos">20:04, 5 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">592 bytes</span> <span dir="ltr" class="mw-plusminus-null mw-diff-bytes" title="592 bytes after change">0</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses">Subpos-WikiSysop moved page <a href="http://subpos.org/wiki/index.php/Main" class="mw-redirect" title="Main">Main</a> to <a href="http://subpos.org/wiki/index.php/About_SubPos" class="mw-redirect" title="About SubPos">About SubPos</a></span></li>
<li data-mw-revid="7"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=7" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=7&amp;oldid=2" title="SubPos">prev</a></span></span><input type="radio" value="7" name="oldid" id="mw-oldid-7" /><input type="radio" value="7" name="diff" id="mw-diff-7" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=7" class="mw-changeslist-date" title="SubPos">20:02, 5 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">592 bytes</span> <span dir="ltr" class="mw-plusminus-null mw-diff-bytes" title="592 bytes after change">0</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses">Subpos-WikiSysop moved page <a href="http://subpos.org/wiki/index.php?title=Home&amp;action=edit&amp;redlink=1" class="new" title="Home (page does not exist)">Home</a> to <a href="http://subpos.org/wiki/index.php/Main" class="mw-redirect" title="Main">Main</a> without leaving a redirect</span></li>
<li data-mw-revid="2"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=2" title="SubPos">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=2&amp;oldid=1" title="SubPos">prev</a></span></span><input type="radio" value="2" name="oldid" id="mw-oldid-2" /><input type="radio" value="2" name="diff" id="mw-diff-2" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=2" class="mw-changeslist-date" title="SubPos">19:52, 5 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <abbr class="minoredit" title="This is a minor edit">m</abbr> <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">592 bytes</span> <span dir="ltr" class="mw-plusminus-null mw-diff-bytes" title="592 bytes after change">0</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses">Blecky moved page <a href="http://subpos.org/wiki/index.php/Main_Page" class="mw-redirect" title="Main Page">Main Page</a> to <a href="http://subpos.org/wiki/index.php?title=Home&amp;action=edit&amp;redlink=1" class="new" title="Home (page does not exist)">Home</a></span></li>
<li data-mw-revid="1"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;diff=463&amp;oldid=1" title="SubPos">cur</a></span><span>prev</span></span><input type="radio" value="1" name="oldid" id="mw-oldid-1" /><input type="radio" value="1" name="diff" id="mw-diff-1" /> <a href="http://subpos.org/wiki/index.php?title=SubPos&amp;oldid=1" class="mw-changeslist-date" title="SubPos">14:45, 5 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php/Special:Contributions/MediaWiki_default" class="mw-userlink mw-anonuserlink" title="Special:Contributions/MediaWiki default"><bdi>MediaWiki default</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:MediaWiki_default&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:MediaWiki default (page does not exist)">talk</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">592 bytes</span> <strong dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="592 bytes after change">+592</strong>‎</li>
</ul>
<div class="mw-history-compareselectedversions"><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form></div>
		
		<div class="printfooter">Retrieved from "<a dir="ltr" href="http://subpos.org/wiki/index.php/SubPos">http://subpos.org/wiki/index.php/SubPos</a>"</div>
		
		<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>
		
		<div class="visualClear"></div>
		
	</div>
</div>

		<div id="mw-navigation">
			<h2>Navigation menu</h2>
			<div id="mw-head">
									<div id="p-personal" role="navigation" aria-labelledby="p-personal-label">
						<h3 id="p-personal-label">Personal tools</h3>
						<ul>
							<li id="pt-login"><a href="http://subpos.org/wiki/index.php?title=Special:UserLogin&amp;returnto=SubPos&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>						</ul>
					</div>
									<div id="left-navigation">
										<div id="p-namespaces" role="navigation" class="vectorTabs" aria-labelledby="p-namespaces-label">
						<h3 id="p-namespaces-label">Namespaces</h3>
						<ul>
							<li id="ca-nstab-main" class="selected"><span><a href="http://subpos.org/wiki/index.php/SubPos" title="View the content page [c]" accesskey="c">Main page</a></span></li><li id="ca-talk" class="new"><span><a href="http://subpos.org/wiki/index.php?title=Talk:SubPos&amp;action=edit&amp;redlink=1" rel="discussion" title="Discussion about the content page (page does not exist) [t]" accesskey="t">Discussion</a></span></li>						</ul>
					</div>
										<div id="p-variants" role="navigation" class="vectorMenu emptyPortlet" aria-labelledby="p-variants-label">
												<input type="checkbox" class="vectorMenuCheckbox" aria-labelledby="p-variants-label" />
						<h3 id="p-variants-label">
							<span>Variants</span>
						</h3>
						<ul class="menu">
													</ul>
					</div>
									</div>
				<div id="right-navigation">
										<div id="p-views" role="navigation" class="vectorTabs" aria-labelledby="p-views-label">
						<h3 id="p-views-label">Views</h3>
						<ul>
							<li id="ca-view" class="collapsible"><span><a href="http://subpos.org/wiki/index.php/SubPos">Read</a></span></li><li id="ca-viewsource" class="collapsible"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;action=edit" title="This page is protected.&#10;You can view its source [e]" accesskey="e">View source</a></span></li><li id="ca-history" class="collapsible selected"><span><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;action=history" title="Past revisions of this page [h]" accesskey="h">View history</a></span></li>						</ul>
					</div>
										<div id="p-cactions" role="navigation" class="vectorMenu emptyPortlet" aria-labelledby="p-cactions-label">
						<input type="checkbox" class="vectorMenuCheckbox" aria-labelledby="p-cactions-label" />
						<h3 id="p-cactions-label"><span>More</span></h3>
						<ul class="menu">
													</ul>
					</div>
										<div id="p-search" role="search">
						<h3>
							<label for="searchInput">Search</label>
						</h3>
						<form action="http://subpos.org/wiki/index.php" id="searchform">
							<div id="simpleSearch">
								<input type="search" name="search" placeholder="Search SubPos" title="Search SubPos [f]" accesskey="f" id="searchInput"/><input type="hidden" value="Special:Search" name="title"/><input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton mw-fallbackSearchButton"/><input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchButton" class="searchButton"/>							</div>
						</form>
					</div>
									</div>
			</div>
			<div id="mw-panel">
				<div id="p-logo" role="banner"><a class="mw-wiki-logo" href="http://subpos.org/wiki/index.php/SubPos" title="Visit the main page"></a></div>
						<div class="portal" role="navigation" id="p-navigation" aria-labelledby="p-navigation-label">
			<h3 id="p-navigation-label">Navigation</h3>
			<div class="body">
								<ul>
					<li id="n-mainpage-description"><a href="http://subpos.org/wiki/index.php/SubPos" title="Visit the main page [z]" accesskey="z">Main page</a></li><li id="n-Documentation"><a href="http://subpos.org/wiki/index.php/SubPos:Documentation">Documentation</a></li><li id="n-Software"><a href="http://subpos.org/wiki/index.php/SubPos:Software">Software</a></li><li id="n-Hardware"><a href="http://subpos.org/wiki/index.php/SubPos:Hardware">Hardware</a></li><li id="n-Repository"><a href="http://subpos.org/wiki/index.php/SubPos:Repository">Repository</a></li><li id="n-Main-site"><a href="https://www.subpos.org/" rel="nofollow">Main site</a></li>				</ul>
							</div>
		</div>
			<div class="portal" role="navigation" id="p-tb" aria-labelledby="p-tb-label">
			<h3 id="p-tb-label">Tools</h3>
			<div class="body">
								<ul>
					<li id="t-whatlinkshere"><a href="http://subpos.org/wiki/index.php/Special:WhatLinksHere/SubPos" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li><li id="t-recentchangeslinked"><a href="http://subpos.org/wiki/index.php/Special:RecentChangesLinked/SubPos" rel="nofollow" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li><li id="feedlinks"><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li><li id="t-specialpages"><a href="http://subpos.org/wiki/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li><li id="t-info"><a href="http://subpos.org/wiki/index.php?title=SubPos&amp;action=info" title="More information about this page">Page information</a></li>				</ul>
							</div>
		</div>
				</div>
		</div>
				<div id="footer" role="contentinfo">
						<ul id="footer-places">
								<li id="footer-places-privacy"><a href="http://subpos.org/wiki/index.php/SubPos:Privacy_policy" title="SubPos:Privacy policy">Privacy policy</a></li>
								<li id="footer-places-about"><a href="http://subpos.org/wiki/index.php/SubPos:About" title="SubPos:About">About SubPos</a></li>
								<li id="footer-places-disclaimer"><a href="http://subpos.org/wiki/index.php/SubPos:General_disclaimer" title="SubPos:General disclaimer">Disclaimers</a></li>
							</ul>
									<div style="clear: both;"></div>
		</div>
		

<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":161});});</script>
</body>

<!-- Mirrored from subpos.org/wiki/index.php?title=SubPos&action=history by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 07 Nov 2019 05:39:08 GMT -->
</html>
