<!DOCTYPE html>
<html class="client-nojs" lang="en" dir="ltr">

<!-- Mirrored from subpos.org/wiki/index.php?title=Path_Loss_Calculation&action=history by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 07 Nov 2019 05:39:20 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
<head>
<meta charset="UTF-8"/>
<title>Revision history of "Path Loss Calculation" - SubPos</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Path_Loss_Calculation","wgTitle":"Path Loss Calculation","wgCurRevisionId":450,"wgRevisionId":0,"wgArticleId":52,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Path_Loss_Calculation","wgRelevantArticleId":52,"wgRequestId":"XcOqqqI8Bos5ze83YO5QbQAAAQ0","wgCSPNonce":false,"wgIsProbablyEditable":false,"wgRelevantPageIsProbablyEditable":false,"wgRestrictionEdit":[],"wgRestrictionMove":[]});mw.loader.state({"site.styles":"ready","noscript":"ready","user.styles":"ready","user":"ready","user.options":"ready","user.tokens":"loading","mediawiki.interface.helpers.styles":"ready","mediawiki.action.history.styles":"ready","mediawiki.special.changeslist":"ready","mediawiki.helplink":"ready","mediawiki.legacy.shared":"ready","mediawiki.legacy.commonPrint":"ready","mediawiki.feedlink":"ready","mediawiki.skinning.interface":"ready","skins.vector.styles":"ready"});mw.loader.implement("user.tokens@0tffind",function($,jQuery,require,module){/*@nomin*/mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
});RLPAGEMODULES=["mediawiki.action.history","site","mediawiki.page.startup","mediawiki.page.ready","mediawiki.searchSuggest","skins.vector.js"];mw.loader.load(RLPAGEMODULES);});</script>
<link rel="stylesheet" href="loadcaad.css?lang=en&amp;modules=mediawiki.action.history.styles%7Cmediawiki.feedlink%2Chelplink%7Cmediawiki.interface.helpers.styles%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.interface%7Cmediawiki.special.changeslist%7Cskins.vector.styles&amp;only=styles&amp;skin=vector"/>
<script async="" src="load3e21.php?lang=en&amp;modules=startup&amp;only=scripts&amp;skin=vector"></script>
<meta name="ResourceLoaderDynamicStyles" content=""/>
<link rel="stylesheet" href="load2f5e.css?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector"/>
<meta name="generator" content="MediaWiki 1.33.0"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="shortcut icon" href="http://subpos.org/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="http://subpos.org/wiki/opensearch_desc.php" title="SubPos (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://subpos.org/wiki/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;Path Loss Calculation&quot; Atom feed" href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="SubPos Atom feed" href="http://subpos.org/wiki/index.php?title=Special:RecentChanges&amp;feed=atom"/>
<!--[if lt IE 9]><script src="/wiki/load.php?lang=en&amp;modules=html5shiv&amp;only=scripts&amp;skin=vector&amp;sync=1"></script><![endif]-->
</head>
<body class="mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject page-Path_Loss_Calculation rootpage-Path_Loss_Calculation skin-vector action-history">
<div id="mw-page-base" class="noprint"></div>
<div id="mw-head-base" class="noprint"></div>
<div id="content" class="mw-body" role="main">
	<a id="top"></a>
	
	<div class="mw-indicators mw-body-content">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="http://meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>

	<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "Path Loss Calculation"</h1>
	
	<div id="bodyContent" class="mw-body-content">
		
		<div id="contentSub"><div class="mw-history-subtitle"><a href="http://subpos.org/wiki/index.php?title=Special:Log&amp;page=Path+Loss+Calculation" title="Special:Log">View logs for this page</a></div></div>
		
		
		
		<div id="jump-to-nav"></div>
		<a class="mw-jump-link" href="#mw-head">Jump to navigation</a>
		<a class="mw-jump-link" href="#p-search">Jump to search</a>
		<div id="mw-content-text"><form action="http://subpos.org/wiki/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Search for revisions</legend>
<input type="hidden" value="Path_Loss_Calculation" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2019" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select> <label for="tagfilter"><a href="http://subpos.org/wiki/index.php/Special:Tags" title="Special:Tags">Tag</a> filter:</label> <input name="tagfilter" size="20" value="" class="mw-tagfilter-input mw-ui-input mw-ui-input-inline" id="tagfilter" /> <input type="submit" value="Show revisions"/>
</fieldset>
</form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div><form action="http://subpos.org/wiki/index.php" id="mw-history-compare">
<input type="hidden" value="Path_Loss_Calculation" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div class="mw-history-compareselectedversions"><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li data-mw-revid="450"><span class="mw-history-histlinks mw-changeslist-links"><span>cur</span><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=450&amp;oldid=449" title="Path Loss Calculation">prev</a></span></span><input type="radio" value="450" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="450" checked="checked" name="diff" id="mw-diff-450" /> <a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;oldid=450" class="mw-changeslist-date" title="Path Loss Calculation">05:55, 14 May 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,241 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,241 bytes after change">+22</span>‎</li>
<li data-mw-revid="449"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=450&amp;oldid=449" title="Path Loss Calculation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=449&amp;oldid=448" title="Path Loss Calculation">prev</a></span></span><input type="radio" value="449" checked="checked" name="oldid" id="mw-oldid-449" /><input type="radio" value="449" name="diff" id="mw-diff-449" /> <a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;oldid=449" class="mw-changeslist-date" title="Path Loss Calculation">05:55, 14 May 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,219 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,219 bytes after change">+116</span>‎</li>
<li data-mw-revid="448"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=450&amp;oldid=448" title="Path Loss Calculation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=448&amp;oldid=444" title="Path Loss Calculation">prev</a></span></span><input type="radio" value="448" name="oldid" id="mw-oldid-448" /><input type="radio" value="448" name="diff" id="mw-diff-448" /> <a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;oldid=448" class="mw-changeslist-date" title="Path Loss Calculation">05:52, 14 May 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,103 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,103 bytes after change">+157</span>‎</li>
<li data-mw-revid="444"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=450&amp;oldid=444" title="Path Loss Calculation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=444&amp;oldid=351" title="Path Loss Calculation">prev</a></span></span><input type="radio" value="444" name="oldid" id="mw-oldid-444" /><input type="radio" value="444" name="diff" id="mw-diff-444" /> <a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;oldid=444" class="mw-changeslist-date" title="Path Loss Calculation">08:44, 7 April 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,946 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,946 bytes after change">+250</span>‎</li>
<li data-mw-revid="351"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=450&amp;oldid=351" title="Path Loss Calculation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=351&amp;oldid=350" title="Path Loss Calculation">prev</a></span></span><input type="radio" value="351" name="oldid" id="mw-oldid-351" /><input type="radio" value="351" name="diff" id="mw-diff-351" /> <a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;oldid=351" class="mw-changeslist-date" title="Path Loss Calculation">21:42, 26 September 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,696 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,696 bytes after change">+162</span>‎</li>
<li data-mw-revid="350"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=450&amp;oldid=350" title="Path Loss Calculation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=350&amp;oldid=338" title="Path Loss Calculation">prev</a></span></span><input type="radio" value="350" name="oldid" id="mw-oldid-350" /><input type="radio" value="350" name="diff" id="mw-diff-350" /> <a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;oldid=350" class="mw-changeslist-date" title="Path Loss Calculation">21:39, 26 September 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,534 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,534 bytes after change">+28</span>‎</li>
<li data-mw-revid="338"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=450&amp;oldid=338" title="Path Loss Calculation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=338&amp;oldid=337" title="Path Loss Calculation">prev</a></span></span><input type="radio" value="338" name="oldid" id="mw-oldid-338" /><input type="radio" value="338" name="diff" id="mw-diff-338" /> <a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;oldid=338" class="mw-changeslist-date" title="Path Loss Calculation">08:58, 23 September 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,506 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,506 bytes after change">+52</span>‎</li>
<li data-mw-revid="337"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=450&amp;oldid=337" title="Path Loss Calculation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=337&amp;oldid=241" title="Path Loss Calculation">prev</a></span></span><input type="radio" value="337" name="oldid" id="mw-oldid-337" /><input type="radio" value="337" name="diff" id="mw-diff-337" /> <a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;oldid=337" class="mw-changeslist-date" title="Path Loss Calculation">08:55, 23 September 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,454 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,454 bytes after change">+183</span>‎</li>
<li data-mw-revid="241"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=450&amp;oldid=241" title="Path Loss Calculation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=241&amp;oldid=240" title="Path Loss Calculation">prev</a></span></span><input type="radio" value="241" name="oldid" id="mw-oldid-241" /><input type="radio" value="241" name="diff" id="mw-diff-241" /> <a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;oldid=241" class="mw-changeslist-date" title="Path Loss Calculation">19:44, 15 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,271 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="1,271 bytes after change">-54</span>‎</li>
<li data-mw-revid="240"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=450&amp;oldid=240" title="Path Loss Calculation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=240&amp;oldid=239" title="Path Loss Calculation">prev</a></span></span><input type="radio" value="240" name="oldid" id="mw-oldid-240" /><input type="radio" value="240" name="diff" id="mw-diff-240" /> <a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;oldid=240" class="mw-changeslist-date" title="Path Loss Calculation">19:30, 15 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,325 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,325 bytes after change">+50</span>‎</li>
<li data-mw-revid="239"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=450&amp;oldid=239" title="Path Loss Calculation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=239&amp;oldid=235" title="Path Loss Calculation">prev</a></span></span><input type="radio" value="239" name="oldid" id="mw-oldid-239" /><input type="radio" value="239" name="diff" id="mw-diff-239" /> <a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;oldid=239" class="mw-changeslist-date" title="Path Loss Calculation">03:23, 15 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,275 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,275 bytes after change">+23</span>‎</li>
<li data-mw-revid="235"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=450&amp;oldid=235" title="Path Loss Calculation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=235&amp;oldid=226" title="Path Loss Calculation">prev</a></span></span><input type="radio" value="235" name="oldid" id="mw-oldid-235" /><input type="radio" value="235" name="diff" id="mw-diff-235" /> <a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;oldid=235" class="mw-changeslist-date" title="Path Loss Calculation">03:11, 15 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,252 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,252 bytes after change">+24</span>‎</li>
<li data-mw-revid="226"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=450&amp;oldid=226" title="Path Loss Calculation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=226&amp;oldid=224" title="Path Loss Calculation">prev</a></span></span><input type="radio" value="226" name="oldid" id="mw-oldid-226" /><input type="radio" value="226" name="diff" id="mw-diff-226" /> <a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;oldid=226" class="mw-changeslist-date" title="Path Loss Calculation">01:43, 15 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,228 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,228 bytes after change">+38</span>‎</li>
<li data-mw-revid="224"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;diff=450&amp;oldid=224" title="Path Loss Calculation">cur</a></span><span>prev</span></span><input type="radio" value="224" name="oldid" id="mw-oldid-224" /><input type="radio" value="224" name="diff" id="mw-diff-224" /> <a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;oldid=224" class="mw-changeslist-date" title="Path Loss Calculation">01:37, 15 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,190 bytes</span> <strong dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,190 bytes after change">+1,190</strong>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses">Created page with &quot;Path loss calculation in the standard defines environment types and provides a best practice(/default application ID 0x0) path loss algorithm (which can change depending on ap...&quot;</span></li>
</ul>
<div class="mw-history-compareselectedversions"><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form></div>
		
		<div class="printfooter">Retrieved from "<a dir="ltr" href="http://subpos.org/wiki/index.php/Path_Loss_Calculation">http://subpos.org/wiki/index.php/Path_Loss_Calculation</a>"</div>
		
		<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>
		
		<div class="visualClear"></div>
		
	</div>
</div>

		<div id="mw-navigation">
			<h2>Navigation menu</h2>
			<div id="mw-head">
									<div id="p-personal" role="navigation" aria-labelledby="p-personal-label">
						<h3 id="p-personal-label">Personal tools</h3>
						<ul>
							<li id="pt-login"><a href="http://subpos.org/wiki/index.php?title=Special:UserLogin&amp;returnto=Path+Loss+Calculation&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>						</ul>
					</div>
									<div id="left-navigation">
										<div id="p-namespaces" role="navigation" class="vectorTabs" aria-labelledby="p-namespaces-label">
						<h3 id="p-namespaces-label">Namespaces</h3>
						<ul>
							<li id="ca-nstab-main" class="selected"><span><a href="http://subpos.org/wiki/index.php/Path_Loss_Calculation" title="View the content page [c]" accesskey="c">Page</a></span></li><li id="ca-talk" class="new"><span><a href="http://subpos.org/wiki/index.php?title=Talk:Path_Loss_Calculation&amp;action=edit&amp;redlink=1" rel="discussion" title="Discussion about the content page (page does not exist) [t]" accesskey="t">Discussion</a></span></li>						</ul>
					</div>
										<div id="p-variants" role="navigation" class="vectorMenu emptyPortlet" aria-labelledby="p-variants-label">
												<input type="checkbox" class="vectorMenuCheckbox" aria-labelledby="p-variants-label" />
						<h3 id="p-variants-label">
							<span>Variants</span>
						</h3>
						<ul class="menu">
													</ul>
					</div>
									</div>
				<div id="right-navigation">
										<div id="p-views" role="navigation" class="vectorTabs" aria-labelledby="p-views-label">
						<h3 id="p-views-label">Views</h3>
						<ul>
							<li id="ca-view" class="collapsible"><span><a href="http://subpos.org/wiki/index.php/Path_Loss_Calculation">Read</a></span></li><li id="ca-viewsource" class="collapsible"><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;action=edit" title="This page is protected.&#10;You can view its source [e]" accesskey="e">View source</a></span></li><li id="ca-history" class="collapsible selected"><span><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;action=history" title="Past revisions of this page [h]" accesskey="h">View history</a></span></li>						</ul>
					</div>
										<div id="p-cactions" role="navigation" class="vectorMenu emptyPortlet" aria-labelledby="p-cactions-label">
						<input type="checkbox" class="vectorMenuCheckbox" aria-labelledby="p-cactions-label" />
						<h3 id="p-cactions-label"><span>More</span></h3>
						<ul class="menu">
													</ul>
					</div>
										<div id="p-search" role="search">
						<h3>
							<label for="searchInput">Search</label>
						</h3>
						<form action="http://subpos.org/wiki/index.php" id="searchform">
							<div id="simpleSearch">
								<input type="search" name="search" placeholder="Search SubPos" title="Search SubPos [f]" accesskey="f" id="searchInput"/><input type="hidden" value="Special:Search" name="title"/><input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton mw-fallbackSearchButton"/><input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchButton" class="searchButton"/>							</div>
						</form>
					</div>
									</div>
			</div>
			<div id="mw-panel">
				<div id="p-logo" role="banner"><a class="mw-wiki-logo" href="http://subpos.org/wiki/index.php/SubPos" title="Visit the main page"></a></div>
						<div class="portal" role="navigation" id="p-navigation" aria-labelledby="p-navigation-label">
			<h3 id="p-navigation-label">Navigation</h3>
			<div class="body">
								<ul>
					<li id="n-mainpage-description"><a href="http://subpos.org/wiki/index.php/SubPos" title="Visit the main page [z]" accesskey="z">Main page</a></li><li id="n-Documentation"><a href="http://subpos.org/wiki/index.php/SubPos:Documentation">Documentation</a></li><li id="n-Software"><a href="http://subpos.org/wiki/index.php/SubPos:Software">Software</a></li><li id="n-Hardware"><a href="http://subpos.org/wiki/index.php/SubPos:Hardware">Hardware</a></li><li id="n-Repository"><a href="http://subpos.org/wiki/index.php/SubPos:Repository">Repository</a></li><li id="n-Main-site"><a href="https://www.subpos.org/" rel="nofollow">Main site</a></li>				</ul>
							</div>
		</div>
			<div class="portal" role="navigation" id="p-tb" aria-labelledby="p-tb-label">
			<h3 id="p-tb-label">Tools</h3>
			<div class="body">
								<ul>
					<li id="t-whatlinkshere"><a href="http://subpos.org/wiki/index.php/Special:WhatLinksHere/Path_Loss_Calculation" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li><li id="t-recentchangeslinked"><a href="http://subpos.org/wiki/index.php/Special:RecentChangesLinked/Path_Loss_Calculation" rel="nofollow" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li><li id="feedlinks"><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li><li id="t-specialpages"><a href="http://subpos.org/wiki/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li><li id="t-info"><a href="http://subpos.org/wiki/index.php?title=Path_Loss_Calculation&amp;action=info" title="More information about this page">Page information</a></li>				</ul>
							</div>
		</div>
				</div>
		</div>
				<div id="footer" role="contentinfo">
						<ul id="footer-places">
								<li id="footer-places-privacy"><a href="http://subpos.org/wiki/index.php/SubPos:Privacy_policy" title="SubPos:Privacy policy">Privacy policy</a></li>
								<li id="footer-places-about"><a href="http://subpos.org/wiki/index.php/SubPos:About" title="SubPos:About">About SubPos</a></li>
								<li id="footer-places-disclaimer"><a href="http://subpos.org/wiki/index.php/SubPos:General_disclaimer" title="SubPos:General disclaimer">Disclaimers</a></li>
							</ul>
									<div style="clear: both;"></div>
		</div>
		

<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":113});});</script>
</body>

<!-- Mirrored from subpos.org/wiki/index.php?title=Path_Loss_Calculation&action=history by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 07 Nov 2019 05:39:20 GMT -->
</html>
