<!DOCTYPE html>
<html class="client-nojs" lang="en" dir="ltr">

<!-- Mirrored from subpos.org/wiki/index.php?title=SubPos:Documentation&action=history by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 07 Nov 2019 05:39:24 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
<head>
<meta charset="UTF-8"/>
<title>Revision history of "SubPos:Documentation" - SubPos</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"Project","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":4,"wgPageName":"SubPos:Documentation","wgTitle":"Documentation","wgCurRevisionId":478,"wgRevisionId":0,"wgArticleId":19,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"SubPos:Documentation","wgRelevantArticleId":19,"wgRequestId":"XcOqWaI8Bos5ze83YO5OMAAAAQU","wgCSPNonce":false,"wgIsProbablyEditable":false,"wgRelevantPageIsProbablyEditable":false,"wgRestrictionEdit":[],"wgRestrictionMove":[]});mw.loader.state({"site.styles":"ready","noscript":"ready","user.styles":"ready","user":"ready","user.options":"ready","user.tokens":"loading","mediawiki.interface.helpers.styles":"ready","mediawiki.action.history.styles":"ready","mediawiki.special.changeslist":"ready","mediawiki.helplink":"ready","mediawiki.legacy.shared":"ready","mediawiki.legacy.commonPrint":"ready","mediawiki.feedlink":"ready","mediawiki.skinning.interface":"ready","skins.vector.styles":"ready"});mw.loader.implement("user.tokens@0tffind",function($,jQuery,require,module){/*@nomin*/mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
});RLPAGEMODULES=["mediawiki.action.history","site","mediawiki.page.startup","mediawiki.page.ready","mediawiki.searchSuggest","skins.vector.js"];mw.loader.load(RLPAGEMODULES);});</script>
<link rel="stylesheet" href="loadcaad.css?lang=en&amp;modules=mediawiki.action.history.styles%7Cmediawiki.feedlink%2Chelplink%7Cmediawiki.interface.helpers.styles%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.interface%7Cmediawiki.special.changeslist%7Cskins.vector.styles&amp;only=styles&amp;skin=vector"/>
<script async="" src="load3e21.php?lang=en&amp;modules=startup&amp;only=scripts&amp;skin=vector"></script>
<meta name="ResourceLoaderDynamicStyles" content=""/>
<link rel="stylesheet" href="load2f5e.css?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector"/>
<meta name="generator" content="MediaWiki 1.33.0"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="shortcut icon" href="http://subpos.org/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="http://subpos.org/wiki/opensearch_desc.php" title="SubPos (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://subpos.org/wiki/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;SubPos:Documentation&quot; Atom feed" href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="SubPos Atom feed" href="http://subpos.org/wiki/index.php?title=Special:RecentChanges&amp;feed=atom"/>
<!--[if lt IE 9]><script src="/wiki/load.php?lang=en&amp;modules=html5shiv&amp;only=scripts&amp;skin=vector&amp;sync=1"></script><![endif]-->
</head>
<body class="mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-4 ns-subject page-SubPos_Documentation rootpage-SubPos_Documentation skin-vector action-history">
<div id="mw-page-base" class="noprint"></div>
<div id="mw-head-base" class="noprint"></div>
<div id="content" class="mw-body" role="main">
	<a id="top"></a>
	
	<div class="mw-indicators mw-body-content">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="http://meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>

	<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "SubPos:Documentation"</h1>
	
	<div id="bodyContent" class="mw-body-content">
		
		<div id="contentSub"><div class="mw-history-subtitle"><a href="http://subpos.org/wiki/index.php?title=Special:Log&amp;page=SubPos%3ADocumentation" title="Special:Log">View logs for this page</a></div></div>
		
		
		
		<div id="jump-to-nav"></div>
		<a class="mw-jump-link" href="#mw-head">Jump to navigation</a>
		<a class="mw-jump-link" href="#p-search">Jump to search</a>
		<div id="mw-content-text"><form action="http://subpos.org/wiki/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Search for revisions</legend>
<input type="hidden" value="SubPos:Documentation" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2019" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select> <label for="tagfilter"><a href="http://subpos.org/wiki/index.php/Special:Tags" title="Special:Tags">Tag</a> filter:</label> <input name="tagfilter" size="20" value="" class="mw-tagfilter-input mw-ui-input mw-ui-input-inline" id="tagfilter" /> <input type="submit" value="Show revisions"/>
</fieldset>
</form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div><form action="http://subpos.org/wiki/index.php" id="mw-history-compare">
<input type="hidden" value="SubPos:Documentation" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div class="mw-history-compareselectedversions"><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li data-mw-revid="478"><span class="mw-history-histlinks mw-changeslist-links"><span>cur</span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=474" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="478" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="478" checked="checked" name="diff" id="mw-diff-478" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=478" class="mw-changeslist-date" title="SubPos:Documentation">10:09, 4 July 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">723 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="723 bytes after change">+22</span>‎</li>
<li data-mw-revid="474"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=474" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=474&amp;oldid=471" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="474" checked="checked" name="oldid" id="mw-oldid-474" /><input type="radio" value="474" name="diff" id="mw-diff-474" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=474" class="mw-changeslist-date" title="SubPos:Documentation">08:23, 4 July 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">701 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="701 bytes after change">+18</span>‎</li>
<li data-mw-revid="471"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=471" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=471&amp;oldid=470" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="471" name="oldid" id="mw-oldid-471" /><input type="radio" value="471" name="diff" id="mw-diff-471" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=471" class="mw-changeslist-date" title="SubPos:Documentation">08:22, 4 July 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">683 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="683 bytes after change">+2</span>‎</li>
<li data-mw-revid="470"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=470" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=470&amp;oldid=469" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="470" name="oldid" id="mw-oldid-470" /><input type="radio" value="470" name="diff" id="mw-diff-470" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=470" class="mw-changeslist-date" title="SubPos:Documentation">08:22, 4 July 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">681 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="681 bytes after change">+15</span>‎</li>
<li data-mw-revid="469"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=469" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=469&amp;oldid=468" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="469" name="oldid" id="mw-oldid-469" /><input type="radio" value="469" name="diff" id="mw-diff-469" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=469" class="mw-changeslist-date" title="SubPos:Documentation">08:21, 4 July 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">666 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="666 bytes after change">-21</span>‎</li>
<li data-mw-revid="468"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=468" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=468&amp;oldid=467" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="468" name="oldid" id="mw-oldid-468" /><input type="radio" value="468" name="diff" id="mw-diff-468" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=468" class="mw-changeslist-date" title="SubPos:Documentation">08:21, 4 July 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">687 bytes</span> <span dir="ltr" class="mw-plusminus-null mw-diff-bytes" title="687 bytes after change">0</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses"><span dir="auto"><span class="autocomment"><a href="http://subpos.org/wiki/index.php/SubPos:Documentation#SubPos_Ranger" title="SubPos:Documentation">→‎SubPos Ranger</a></span></span></span></li>
<li data-mw-revid="467"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=467" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=467&amp;oldid=466" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="467" name="oldid" id="mw-oldid-467" /><input type="radio" value="467" name="diff" id="mw-diff-467" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=467" class="mw-changeslist-date" title="SubPos:Documentation">08:21, 4 July 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">687 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="687 bytes after change">+127</span>‎</li>
<li data-mw-revid="466"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=466" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=466&amp;oldid=465" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="466" name="oldid" id="mw-oldid-466" /><input type="radio" value="466" name="diff" id="mw-diff-466" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=466" class="mw-changeslist-date" title="SubPos:Documentation">08:19, 4 July 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">560 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="560 bytes after change">+18</span>‎</li>
<li data-mw-revid="465"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=465" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=465&amp;oldid=447" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="465" name="oldid" id="mw-oldid-465" /><input type="radio" value="465" name="diff" id="mw-diff-465" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=465" class="mw-changeslist-date" title="SubPos:Documentation">08:19, 4 July 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">542 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="542 bytes after change">+73</span>‎</li>
<li data-mw-revid="447"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=447" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=447&amp;oldid=417" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="447" name="oldid" id="mw-oldid-447" /><input type="radio" value="447" name="diff" id="mw-diff-447" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=447" class="mw-changeslist-date" title="SubPos:Documentation">01:38, 13 May 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">469 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="469 bytes after change">+83</span>‎</li>
<li data-mw-revid="417"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=417" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=417&amp;oldid=413" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="417" name="oldid" id="mw-oldid-417" /><input type="radio" value="417" name="diff" id="mw-diff-417" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=417" class="mw-changeslist-date" title="SubPos:Documentation">07:08, 24 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">386 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="386 bytes after change">-29</span>‎</li>
<li data-mw-revid="413"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=413" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=413&amp;oldid=339" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="413" name="oldid" id="mw-oldid-413" /><input type="radio" value="413" name="diff" id="mw-diff-413" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=413" class="mw-changeslist-date" title="SubPos:Documentation">06:31, 24 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">415 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="415 bytes after change">-57</span>‎</li>
<li data-mw-revid="339"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=339" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=339&amp;oldid=321" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="339" name="oldid" id="mw-oldid-339" /><input type="radio" value="339" name="diff" id="mw-diff-339" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=339" class="mw-changeslist-date" title="SubPos:Documentation">09:00, 23 September 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">472 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="472 bytes after change">+29</span>‎</li>
<li data-mw-revid="321"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=321" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=321&amp;oldid=307" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="321" name="oldid" id="mw-oldid-321" /><input type="radio" value="321" name="diff" id="mw-diff-321" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=321" class="mw-changeslist-date" title="SubPos:Documentation">19:23, 7 September 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">443 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="443 bytes after change">+72</span>‎</li>
<li data-mw-revid="307"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=307" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=307&amp;oldid=280" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="307" name="oldid" id="mw-oldid-307" /><input type="radio" value="307" name="diff" id="mw-diff-307" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=307" class="mw-changeslist-date" title="SubPos:Documentation">07:50, 20 August 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">371 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="371 bytes after change">+47</span>‎</li>
<li data-mw-revid="280"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=280" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=280&amp;oldid=237" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="280" name="oldid" id="mw-oldid-280" /><input type="radio" value="280" name="diff" id="mw-diff-280" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=280" class="mw-changeslist-date" title="SubPos:Documentation">22:36, 21 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">324 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="324 bytes after change">+33</span>‎</li>
<li data-mw-revid="237"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=237" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=237&amp;oldid=236" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="237" name="oldid" id="mw-oldid-237" /><input type="radio" value="237" name="diff" id="mw-diff-237" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=237" class="mw-changeslist-date" title="SubPos:Documentation">03:13, 15 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">291 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="291 bytes after change">-43</span>‎</li>
<li data-mw-revid="236"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=236" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=236&amp;oldid=163" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="236" name="oldid" id="mw-oldid-236" /><input type="radio" value="236" name="diff" id="mw-diff-236" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=236" class="mw-changeslist-date" title="SubPos:Documentation">03:12, 15 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">334 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="334 bytes after change">+1</span>‎</li>
<li data-mw-revid="163"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=163" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=163&amp;oldid=154" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="163" name="oldid" id="mw-oldid-163" /><input type="radio" value="163" name="diff" id="mw-diff-163" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=163" class="mw-changeslist-date" title="SubPos:Documentation">06:41, 17 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">333 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="333 bytes after change">+21</span>‎</li>
<li data-mw-revid="154"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=154" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=154&amp;oldid=150" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="154" name="oldid" id="mw-oldid-154" /><input type="radio" value="154" name="diff" id="mw-diff-154" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=154" class="mw-changeslist-date" title="SubPos:Documentation">05:29, 17 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">312 bytes</span> <span dir="ltr" class="mw-plusminus-null mw-diff-bytes" title="312 bytes after change">0</span>‎</li>
<li data-mw-revid="150"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=150" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=150&amp;oldid=149" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="150" name="oldid" id="mw-oldid-150" /><input type="radio" value="150" name="diff" id="mw-diff-150" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=150" class="mw-changeslist-date" title="SubPos:Documentation">05:23, 17 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">312 bytes</span> <span dir="ltr" class="mw-plusminus-null mw-diff-bytes" title="312 bytes after change">0</span>‎</li>
<li data-mw-revid="149"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=149" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=149&amp;oldid=127" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="149" name="oldid" id="mw-oldid-149" /><input type="radio" value="149" name="diff" id="mw-diff-149" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=149" class="mw-changeslist-date" title="SubPos:Documentation">05:22, 17 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">312 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="312 bytes after change">-15</span>‎</li>
<li data-mw-revid="127"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=127" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=127&amp;oldid=126" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="127" name="oldid" id="mw-oldid-127" /><input type="radio" value="127" name="diff" id="mw-diff-127" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=127" class="mw-changeslist-date" title="SubPos:Documentation">07:53, 15 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">327 bytes</span> <span dir="ltr" class="mw-plusminus-null mw-diff-bytes" title="327 bytes after change">0</span>‎</li>
<li data-mw-revid="126"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=126" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=126&amp;oldid=103" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="126" name="oldid" id="mw-oldid-126" /><input type="radio" value="126" name="diff" id="mw-diff-126" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=126" class="mw-changeslist-date" title="SubPos:Documentation">07:50, 15 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">327 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="327 bytes after change">-3</span>‎</li>
<li data-mw-revid="103"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=103" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=103&amp;oldid=88" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="103" name="oldid" id="mw-oldid-103" /><input type="radio" value="103" name="diff" id="mw-diff-103" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=103" class="mw-changeslist-date" title="SubPos:Documentation">08:13, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">330 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="330 bytes after change">+67</span>‎</li>
<li data-mw-revid="88"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=88" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=88&amp;oldid=69" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="88" name="oldid" id="mw-oldid-88" /><input type="radio" value="88" name="diff" id="mw-diff-88" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=88" class="mw-changeslist-date" title="SubPos:Documentation">07:39, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">263 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="263 bytes after change">+47</span>‎</li>
<li data-mw-revid="69"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=69" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=69&amp;oldid=67" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="69" name="oldid" id="mw-oldid-69" /><input type="radio" value="69" name="diff" id="mw-diff-69" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=69" class="mw-changeslist-date" title="SubPos:Documentation">07:10, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">216 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="216 bytes after change">+19</span>‎</li>
<li data-mw-revid="67"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=67" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=67&amp;oldid=64" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="67" name="oldid" id="mw-oldid-67" /><input type="radio" value="67" name="diff" id="mw-diff-67" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=67" class="mw-changeslist-date" title="SubPos:Documentation">07:04, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">197 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="197 bytes after change">+13</span>‎</li>
<li data-mw-revid="64"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=64" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=64&amp;oldid=63" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="64" name="oldid" id="mw-oldid-64" /><input type="radio" value="64" name="diff" id="mw-diff-64" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=64" class="mw-changeslist-date" title="SubPos:Documentation">07:02, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">184 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="184 bytes after change">+49</span>‎</li>
<li data-mw-revid="63"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=63" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=63&amp;oldid=56" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="63" name="oldid" id="mw-oldid-63" /><input type="radio" value="63" name="diff" id="mw-diff-63" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=63" class="mw-changeslist-date" title="SubPos:Documentation">07:01, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">135 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="135 bytes after change">+57</span>‎</li>
<li data-mw-revid="56"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=56" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=56&amp;oldid=55" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="56" name="oldid" id="mw-oldid-56" /><input type="radio" value="56" name="diff" id="mw-diff-56" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=56" class="mw-changeslist-date" title="SubPos:Documentation">06:48, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">78 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="78 bytes after change">+1</span>‎</li>
<li data-mw-revid="55"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=55" title="SubPos:Documentation">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=55&amp;oldid=52" title="SubPos:Documentation">prev</a></span></span><input type="radio" value="55" name="oldid" id="mw-oldid-55" /><input type="radio" value="55" name="diff" id="mw-diff-55" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=55" class="mw-changeslist-date" title="SubPos:Documentation">06:48, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">77 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="77 bytes after change">+36</span>‎</li>
<li data-mw-revid="52"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;diff=478&amp;oldid=52" title="SubPos:Documentation">cur</a></span><span>prev</span></span><input type="radio" value="52" name="oldid" id="mw-oldid-52" /><input type="radio" value="52" name="diff" id="mw-diff-52" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;oldid=52" class="mw-changeslist-date" title="SubPos:Documentation">06:35, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">41 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="41 bytes after change">+41</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses">Created page with &quot;<a href="http://subpos.org/wiki/index.php/Coded_Beacon_Frame" title="Coded Beacon Frame">Coded Beacon Frame</a>&quot;</span></li>
</ul>
<div class="mw-history-compareselectedversions"><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form></div>
		
		<div class="printfooter">Retrieved from "<a dir="ltr" href="http://subpos.org/wiki/index.php/SubPos:Documentation">http://subpos.org/wiki/index.php/SubPos:Documentation</a>"</div>
		
		<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>
		
		<div class="visualClear"></div>
		
	</div>
</div>

		<div id="mw-navigation">
			<h2>Navigation menu</h2>
			<div id="mw-head">
									<div id="p-personal" role="navigation" aria-labelledby="p-personal-label">
						<h3 id="p-personal-label">Personal tools</h3>
						<ul>
							<li id="pt-login"><a href="http://subpos.org/wiki/index.php?title=Special:UserLogin&amp;returnto=SubPos%3ADocumentation&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>						</ul>
					</div>
									<div id="left-navigation">
										<div id="p-namespaces" role="navigation" class="vectorTabs" aria-labelledby="p-namespaces-label">
						<h3 id="p-namespaces-label">Namespaces</h3>
						<ul>
							<li id="ca-nstab-project" class="selected"><span><a href="http://subpos.org/wiki/index.php/SubPos:Documentation" title="View the project page [a]" accesskey="a">Project page</a></span></li><li id="ca-talk" class="new"><span><a href="http://subpos.org/wiki/index.php?title=SubPos_talk:Documentation&amp;action=edit&amp;redlink=1" rel="discussion" title="Discussion about the content page (page does not exist) [t]" accesskey="t">Discussion</a></span></li>						</ul>
					</div>
										<div id="p-variants" role="navigation" class="vectorMenu emptyPortlet" aria-labelledby="p-variants-label">
												<input type="checkbox" class="vectorMenuCheckbox" aria-labelledby="p-variants-label" />
						<h3 id="p-variants-label">
							<span>Variants</span>
						</h3>
						<ul class="menu">
													</ul>
					</div>
									</div>
				<div id="right-navigation">
										<div id="p-views" role="navigation" class="vectorTabs" aria-labelledby="p-views-label">
						<h3 id="p-views-label">Views</h3>
						<ul>
							<li id="ca-view" class="collapsible"><span><a href="http://subpos.org/wiki/index.php/SubPos:Documentation">Read</a></span></li><li id="ca-viewsource" class="collapsible"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;action=edit" title="This page is protected.&#10;You can view its source [e]" accesskey="e">View source</a></span></li><li id="ca-history" class="collapsible selected"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;action=history" title="Past revisions of this page [h]" accesskey="h">View history</a></span></li>						</ul>
					</div>
										<div id="p-cactions" role="navigation" class="vectorMenu emptyPortlet" aria-labelledby="p-cactions-label">
						<input type="checkbox" class="vectorMenuCheckbox" aria-labelledby="p-cactions-label" />
						<h3 id="p-cactions-label"><span>More</span></h3>
						<ul class="menu">
													</ul>
					</div>
										<div id="p-search" role="search">
						<h3>
							<label for="searchInput">Search</label>
						</h3>
						<form action="http://subpos.org/wiki/index.php" id="searchform">
							<div id="simpleSearch">
								<input type="search" name="search" placeholder="Search SubPos" title="Search SubPos [f]" accesskey="f" id="searchInput"/><input type="hidden" value="Special:Search" name="title"/><input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton mw-fallbackSearchButton"/><input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchButton" class="searchButton"/>							</div>
						</form>
					</div>
									</div>
			</div>
			<div id="mw-panel">
				<div id="p-logo" role="banner"><a class="mw-wiki-logo" href="http://subpos.org/wiki/index.php/SubPos" title="Visit the main page"></a></div>
						<div class="portal" role="navigation" id="p-navigation" aria-labelledby="p-navigation-label">
			<h3 id="p-navigation-label">Navigation</h3>
			<div class="body">
								<ul>
					<li id="n-mainpage-description"><a href="http://subpos.org/wiki/index.php/SubPos" title="Visit the main page [z]" accesskey="z">Main page</a></li><li id="n-Documentation"><a href="http://subpos.org/wiki/index.php/SubPos:Documentation">Documentation</a></li><li id="n-Software"><a href="http://subpos.org/wiki/index.php/SubPos:Software">Software</a></li><li id="n-Hardware"><a href="http://subpos.org/wiki/index.php/SubPos:Hardware">Hardware</a></li><li id="n-Repository"><a href="http://subpos.org/wiki/index.php/SubPos:Repository">Repository</a></li><li id="n-Main-site"><a href="https://www.subpos.org/" rel="nofollow">Main site</a></li>				</ul>
							</div>
		</div>
			<div class="portal" role="navigation" id="p-tb" aria-labelledby="p-tb-label">
			<h3 id="p-tb-label">Tools</h3>
			<div class="body">
								<ul>
					<li id="t-whatlinkshere"><a href="http://subpos.org/wiki/index.php/Special:WhatLinksHere/SubPos:Documentation" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li><li id="t-recentchangeslinked"><a href="http://subpos.org/wiki/index.php/Special:RecentChangesLinked/SubPos:Documentation" rel="nofollow" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li><li id="feedlinks"><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li><li id="t-specialpages"><a href="http://subpos.org/wiki/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li><li id="t-info"><a href="http://subpos.org/wiki/index.php?title=SubPos:Documentation&amp;action=info" title="More information about this page">Page information</a></li>				</ul>
							</div>
		</div>
				</div>
		</div>
				<div id="footer" role="contentinfo">
						<ul id="footer-places">
								<li id="footer-places-privacy"><a href="http://subpos.org/wiki/index.php/SubPos:Privacy_policy" title="SubPos:Privacy policy">Privacy policy</a></li>
								<li id="footer-places-about"><a href="http://subpos.org/wiki/index.php/SubPos:About" title="SubPos:About">About SubPos</a></li>
								<li id="footer-places-disclaimer"><a href="http://subpos.org/wiki/index.php/SubPos:General_disclaimer" title="SubPos:General disclaimer">Disclaimers</a></li>
							</ul>
									<div style="clear: both;"></div>
		</div>
		

<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":130});});</script>
</body>

<!-- Mirrored from subpos.org/wiki/index.php?title=SubPos:Documentation&action=history by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 07 Nov 2019 05:39:24 GMT -->
</html>
