<!DOCTYPE html>
<html class="client-nojs" lang="en" dir="ltr">

<!-- Mirrored from subpos.org/wiki/index.php?title=SubPos:How_it_works&action=history by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 07 Nov 2019 05:39:39 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
<head>
<meta charset="UTF-8"/>
<title>Revision history of "SubPos:How it works" - SubPos</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"Project","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":4,"wgPageName":"SubPos:How_it_works","wgTitle":"How it works","wgCurRevisionId":300,"wgRevisionId":0,"wgArticleId":17,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"SubPos:How_it_works","wgRelevantArticleId":17,"wgRequestId":"XcOrEaI8Bos5ze83YO5SpQAAAQ0","wgCSPNonce":false,"wgIsProbablyEditable":false,"wgRelevantPageIsProbablyEditable":false,"wgRestrictionEdit":[],"wgRestrictionMove":[]});mw.loader.state({"site.styles":"ready","noscript":"ready","user.styles":"ready","user":"ready","user.options":"ready","user.tokens":"loading","mediawiki.interface.helpers.styles":"ready","mediawiki.action.history.styles":"ready","mediawiki.special.changeslist":"ready","mediawiki.helplink":"ready","mediawiki.legacy.shared":"ready","mediawiki.legacy.commonPrint":"ready","mediawiki.feedlink":"ready","mediawiki.skinning.interface":"ready","skins.vector.styles":"ready"});mw.loader.implement("user.tokens@0tffind",function($,jQuery,require,module){/*@nomin*/mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
});RLPAGEMODULES=["mediawiki.action.history","site","mediawiki.page.startup","mediawiki.page.ready","mediawiki.searchSuggest","skins.vector.js"];mw.loader.load(RLPAGEMODULES);});</script>
<link rel="stylesheet" href="loadcaad.css?lang=en&amp;modules=mediawiki.action.history.styles%7Cmediawiki.feedlink%2Chelplink%7Cmediawiki.interface.helpers.styles%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.interface%7Cmediawiki.special.changeslist%7Cskins.vector.styles&amp;only=styles&amp;skin=vector"/>
<script async="" src="load3e21.php?lang=en&amp;modules=startup&amp;only=scripts&amp;skin=vector"></script>
<meta name="ResourceLoaderDynamicStyles" content=""/>
<link rel="stylesheet" href="load2f5e.css?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector"/>
<meta name="generator" content="MediaWiki 1.33.0"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="shortcut icon" href="http://subpos.org/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="http://subpos.org/wiki/opensearch_desc.php" title="SubPos (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://subpos.org/wiki/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;SubPos:How it works&quot; Atom feed" href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="SubPos Atom feed" href="http://subpos.org/wiki/index.php?title=Special:RecentChanges&amp;feed=atom"/>
<!--[if lt IE 9]><script src="/wiki/load.php?lang=en&amp;modules=html5shiv&amp;only=scripts&amp;skin=vector&amp;sync=1"></script><![endif]-->
</head>
<body class="mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-4 ns-subject page-SubPos_How_it_works rootpage-SubPos_How_it_works skin-vector action-history">
<div id="mw-page-base" class="noprint"></div>
<div id="mw-head-base" class="noprint"></div>
<div id="content" class="mw-body" role="main">
	<a id="top"></a>
	
	<div class="mw-indicators mw-body-content">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="http://meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>

	<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "SubPos:How it works"</h1>
	
	<div id="bodyContent" class="mw-body-content">
		
		<div id="contentSub"><div class="mw-history-subtitle"><a href="http://subpos.org/wiki/index.php?title=Special:Log&amp;page=SubPos%3AHow+it+works" title="Special:Log">View logs for this page</a></div></div>
		
		
		
		<div id="jump-to-nav"></div>
		<a class="mw-jump-link" href="#mw-head">Jump to navigation</a>
		<a class="mw-jump-link" href="#p-search">Jump to search</a>
		<div id="mw-content-text"><form action="http://subpos.org/wiki/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Search for revisions</legend>
<input type="hidden" value="SubPos:How_it_works" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2019" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select> <label for="tagfilter"><a href="http://subpos.org/wiki/index.php/Special:Tags" title="Special:Tags">Tag</a> filter:</label> <input name="tagfilter" size="20" value="" class="mw-tagfilter-input mw-ui-input mw-ui-input-inline" id="tagfilter" /> <input type="submit" value="Show revisions"/>
</fieldset>
</form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div><form action="http://subpos.org/wiki/index.php" id="mw-history-compare">
<input type="hidden" value="SubPos:How_it_works" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div class="mw-history-compareselectedversions"><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li data-mw-revid="300"><span class="mw-history-histlinks mw-changeslist-links"><span>cur</span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=300&amp;oldid=299" title="SubPos:How it works">prev</a></span></span><input type="radio" value="300" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="300" checked="checked" name="diff" id="mw-diff-300" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;oldid=300" class="mw-changeslist-date" title="SubPos:How it works">23:14, 15 August 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,492 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,492 bytes after change">+62</span>‎</li>
<li data-mw-revid="299"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=300&amp;oldid=299" title="SubPos:How it works">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=299&amp;oldid=298" title="SubPos:How it works">prev</a></span></span><input type="radio" value="299" checked="checked" name="oldid" id="mw-oldid-299" /><input type="radio" value="299" name="diff" id="mw-diff-299" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;oldid=299" class="mw-changeslist-date" title="SubPos:How it works">22:49, 15 August 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,430 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,430 bytes after change">+20</span>‎</li>
<li data-mw-revid="298"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=300&amp;oldid=298" title="SubPos:How it works">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=298&amp;oldid=295" title="SubPos:How it works">prev</a></span></span><input type="radio" value="298" name="oldid" id="mw-oldid-298" /><input type="radio" value="298" name="diff" id="mw-diff-298" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;oldid=298" class="mw-changeslist-date" title="SubPos:How it works">22:48, 15 August 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,410 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,410 bytes after change">+167</span>‎</li>
<li data-mw-revid="295"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=300&amp;oldid=295" title="SubPos:How it works">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=295&amp;oldid=294" title="SubPos:How it works">prev</a></span></span><input type="radio" value="295" name="oldid" id="mw-oldid-295" /><input type="radio" value="295" name="diff" id="mw-diff-295" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;oldid=295" class="mw-changeslist-date" title="SubPos:How it works">10:53, 15 August 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,243 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,243 bytes after change">+41</span>‎</li>
<li data-mw-revid="294"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=300&amp;oldid=294" title="SubPos:How it works">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=294&amp;oldid=290" title="SubPos:How it works">prev</a></span></span><input type="radio" value="294" name="oldid" id="mw-oldid-294" /><input type="radio" value="294" name="diff" id="mw-diff-294" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;oldid=294" class="mw-changeslist-date" title="SubPos:How it works">10:35, 3 August 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,202 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,202 bytes after change">+8</span>‎</li>
<li data-mw-revid="290"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=300&amp;oldid=290" title="SubPos:How it works">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=290&amp;oldid=254" title="SubPos:How it works">prev</a></span></span><input type="radio" value="290" name="oldid" id="mw-oldid-290" /><input type="radio" value="290" name="diff" id="mw-diff-290" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;oldid=290" class="mw-changeslist-date" title="SubPos:How it works">06:35, 30 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,194 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,194 bytes after change">+12</span>‎</li>
<li data-mw-revid="254"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=300&amp;oldid=254" title="SubPos:How it works">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=254&amp;oldid=253" title="SubPos:How it works">prev</a></span></span><input type="radio" value="254" name="oldid" id="mw-oldid-254" /><input type="radio" value="254" name="diff" id="mw-diff-254" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;oldid=254" class="mw-changeslist-date" title="SubPos:How it works">05:37, 20 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,182 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,182 bytes after change">+5</span>‎</li>
<li data-mw-revid="253"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=300&amp;oldid=253" title="SubPos:How it works">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=253&amp;oldid=251" title="SubPos:How it works">prev</a></span></span><input type="radio" value="253" name="oldid" id="mw-oldid-253" /><input type="radio" value="253" name="diff" id="mw-diff-253" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;oldid=253" class="mw-changeslist-date" title="SubPos:How it works">05:35, 20 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,177 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="3,177 bytes after change">-86</span>‎</li>
<li data-mw-revid="251"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=300&amp;oldid=251" title="SubPos:How it works">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=251&amp;oldid=247" title="SubPos:How it works">prev</a></span></span><input type="radio" value="251" name="oldid" id="mw-oldid-251" /><input type="radio" value="251" name="diff" id="mw-diff-251" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;oldid=251" class="mw-changeslist-date" title="SubPos:How it works">05:33, 20 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,263 bytes</span> <span dir="ltr" class="mw-plusminus-null mw-diff-bytes" title="3,263 bytes after change">0</span>‎</li>
<li data-mw-revid="247"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=300&amp;oldid=247" title="SubPos:How it works">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=247&amp;oldid=113" title="SubPos:How it works">prev</a></span></span><input type="radio" value="247" name="oldid" id="mw-oldid-247" /><input type="radio" value="247" name="diff" id="mw-diff-247" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;oldid=247" class="mw-changeslist-date" title="SubPos:How it works">05:31, 20 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,263 bytes</span> <strong dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,263 bytes after change">+2,052</strong>‎</li>
<li data-mw-revid="113"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=300&amp;oldid=113" title="SubPos:How it works">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=113&amp;oldid=108" title="SubPos:How it works">prev</a></span></span><input type="radio" value="113" name="oldid" id="mw-oldid-113" /><input type="radio" value="113" name="diff" id="mw-diff-113" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;oldid=113" class="mw-changeslist-date" title="SubPos:How it works">23:01, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,211 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,211 bytes after change">+23</span>‎</li>
<li data-mw-revid="108"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=300&amp;oldid=108" title="SubPos:How it works">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=108&amp;oldid=75" title="SubPos:How it works">prev</a></span></span><input type="radio" value="108" name="oldid" id="mw-oldid-108" /><input type="radio" value="108" name="diff" id="mw-diff-108" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;oldid=108" class="mw-changeslist-date" title="SubPos:How it works">08:56, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,188 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,188 bytes after change">+64</span>‎</li>
<li data-mw-revid="75"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=300&amp;oldid=75" title="SubPos:How it works">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=75&amp;oldid=74" title="SubPos:How it works">prev</a></span></span><input type="radio" value="75" name="oldid" id="mw-oldid-75" /><input type="radio" value="75" name="diff" id="mw-diff-75" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;oldid=75" class="mw-changeslist-date" title="SubPos:How it works">07:15, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,124 bytes</span> <span dir="ltr" class="mw-plusminus-null mw-diff-bytes" title="1,124 bytes after change">0</span>‎</li>
<li data-mw-revid="74"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=300&amp;oldid=74" title="SubPos:How it works">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=74&amp;oldid=73" title="SubPos:How it works">prev</a></span></span><input type="radio" value="74" name="oldid" id="mw-oldid-74" /><input type="radio" value="74" name="diff" id="mw-diff-74" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;oldid=74" class="mw-changeslist-date" title="SubPos:How it works">07:15, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,124 bytes</span> <span dir="ltr" class="mw-plusminus-null mw-diff-bytes" title="1,124 bytes after change">0</span>‎</li>
<li data-mw-revid="73"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=300&amp;oldid=73" title="SubPos:How it works">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=73&amp;oldid=72" title="SubPos:How it works">prev</a></span></span><input type="radio" value="73" name="oldid" id="mw-oldid-73" /><input type="radio" value="73" name="diff" id="mw-diff-73" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;oldid=73" class="mw-changeslist-date" title="SubPos:How it works">07:15, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,124 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="1,124 bytes after change">-2</span>‎</li>
<li data-mw-revid="72"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=300&amp;oldid=72" title="SubPos:How it works">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=72&amp;oldid=50" title="SubPos:How it works">prev</a></span></span><input type="radio" value="72" name="oldid" id="mw-oldid-72" /><input type="radio" value="72" name="diff" id="mw-diff-72" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;oldid=72" class="mw-changeslist-date" title="SubPos:How it works">07:13, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,126 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,126 bytes after change">+8</span>‎</li>
<li data-mw-revid="50"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=300&amp;oldid=50" title="SubPos:How it works">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=50&amp;oldid=48" title="SubPos:How it works">prev</a></span></span><input type="radio" value="50" name="oldid" id="mw-oldid-50" /><input type="radio" value="50" name="diff" id="mw-diff-50" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;oldid=50" class="mw-changeslist-date" title="SubPos:How it works">06:34, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,118 bytes</span> <strong dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,118 bytes after change">+1,089</strong>‎</li>
<li data-mw-revid="48"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;diff=300&amp;oldid=48" title="SubPos:How it works">cur</a></span><span>prev</span></span><input type="radio" value="48" name="oldid" id="mw-oldid-48" /><input type="radio" value="48" name="diff" id="mw-diff-48" /> <a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;oldid=48" class="mw-changeslist-date" title="SubPos:How it works">06:31, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">29 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="29 bytes after change">+29</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses">Created page with &quot;<a href="http://subpos.org/wiki/index.php/File:How_subpos_works.png" title="File:How subpos works.png">File:How_subpos_works.png</a>&quot;</span></li>
</ul>
<div class="mw-history-compareselectedversions"><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form></div>
		
		<div class="printfooter">Retrieved from "<a dir="ltr" href="http://subpos.org/wiki/index.php/SubPos:How_it_works">http://subpos.org/wiki/index.php/SubPos:How_it_works</a>"</div>
		
		<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>
		
		<div class="visualClear"></div>
		
	</div>
</div>

		<div id="mw-navigation">
			<h2>Navigation menu</h2>
			<div id="mw-head">
									<div id="p-personal" role="navigation" aria-labelledby="p-personal-label">
						<h3 id="p-personal-label">Personal tools</h3>
						<ul>
							<li id="pt-login"><a href="http://subpos.org/wiki/index.php?title=Special:UserLogin&amp;returnto=SubPos%3AHow+it+works&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>						</ul>
					</div>
									<div id="left-navigation">
										<div id="p-namespaces" role="navigation" class="vectorTabs" aria-labelledby="p-namespaces-label">
						<h3 id="p-namespaces-label">Namespaces</h3>
						<ul>
							<li id="ca-nstab-project" class="selected"><span><a href="http://subpos.org/wiki/index.php/SubPos:How_it_works" title="View the project page [a]" accesskey="a">Project page</a></span></li><li id="ca-talk" class="new"><span><a href="http://subpos.org/wiki/index.php?title=SubPos_talk:How_it_works&amp;action=edit&amp;redlink=1" rel="discussion" title="Discussion about the content page (page does not exist) [t]" accesskey="t">Discussion</a></span></li>						</ul>
					</div>
										<div id="p-variants" role="navigation" class="vectorMenu emptyPortlet" aria-labelledby="p-variants-label">
												<input type="checkbox" class="vectorMenuCheckbox" aria-labelledby="p-variants-label" />
						<h3 id="p-variants-label">
							<span>Variants</span>
						</h3>
						<ul class="menu">
													</ul>
					</div>
									</div>
				<div id="right-navigation">
										<div id="p-views" role="navigation" class="vectorTabs" aria-labelledby="p-views-label">
						<h3 id="p-views-label">Views</h3>
						<ul>
							<li id="ca-view" class="collapsible"><span><a href="http://subpos.org/wiki/index.php/SubPos:How_it_works">Read</a></span></li><li id="ca-viewsource" class="collapsible"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;action=edit" title="This page is protected.&#10;You can view its source [e]" accesskey="e">View source</a></span></li><li id="ca-history" class="collapsible selected"><span><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;action=history" title="Past revisions of this page [h]" accesskey="h">View history</a></span></li>						</ul>
					</div>
										<div id="p-cactions" role="navigation" class="vectorMenu emptyPortlet" aria-labelledby="p-cactions-label">
						<input type="checkbox" class="vectorMenuCheckbox" aria-labelledby="p-cactions-label" />
						<h3 id="p-cactions-label"><span>More</span></h3>
						<ul class="menu">
													</ul>
					</div>
										<div id="p-search" role="search">
						<h3>
							<label for="searchInput">Search</label>
						</h3>
						<form action="http://subpos.org/wiki/index.php" id="searchform">
							<div id="simpleSearch">
								<input type="search" name="search" placeholder="Search SubPos" title="Search SubPos [f]" accesskey="f" id="searchInput"/><input type="hidden" value="Special:Search" name="title"/><input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton mw-fallbackSearchButton"/><input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchButton" class="searchButton"/>							</div>
						</form>
					</div>
									</div>
			</div>
			<div id="mw-panel">
				<div id="p-logo" role="banner"><a class="mw-wiki-logo" href="http://subpos.org/wiki/index.php/SubPos" title="Visit the main page"></a></div>
						<div class="portal" role="navigation" id="p-navigation" aria-labelledby="p-navigation-label">
			<h3 id="p-navigation-label">Navigation</h3>
			<div class="body">
								<ul>
					<li id="n-mainpage-description"><a href="http://subpos.org/wiki/index.php/SubPos" title="Visit the main page [z]" accesskey="z">Main page</a></li><li id="n-Documentation"><a href="http://subpos.org/wiki/index.php/SubPos:Documentation">Documentation</a></li><li id="n-Software"><a href="http://subpos.org/wiki/index.php/SubPos:Software">Software</a></li><li id="n-Hardware"><a href="http://subpos.org/wiki/index.php/SubPos:Hardware">Hardware</a></li><li id="n-Repository"><a href="http://subpos.org/wiki/index.php/SubPos:Repository">Repository</a></li><li id="n-Main-site"><a href="https://www.subpos.org/" rel="nofollow">Main site</a></li>				</ul>
							</div>
		</div>
			<div class="portal" role="navigation" id="p-tb" aria-labelledby="p-tb-label">
			<h3 id="p-tb-label">Tools</h3>
			<div class="body">
								<ul>
					<li id="t-whatlinkshere"><a href="http://subpos.org/wiki/index.php/Special:WhatLinksHere/SubPos:How_it_works" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li><li id="t-recentchangeslinked"><a href="http://subpos.org/wiki/index.php/Special:RecentChangesLinked/SubPos:How_it_works" rel="nofollow" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li><li id="feedlinks"><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li><li id="t-specialpages"><a href="http://subpos.org/wiki/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li><li id="t-info"><a href="http://subpos.org/wiki/index.php?title=SubPos:How_it_works&amp;action=info" title="More information about this page">Page information</a></li>				</ul>
							</div>
		</div>
				</div>
		</div>
				<div id="footer" role="contentinfo">
						<ul id="footer-places">
								<li id="footer-places-privacy"><a href="http://subpos.org/wiki/index.php/SubPos:Privacy_policy" title="SubPos:Privacy policy">Privacy policy</a></li>
								<li id="footer-places-about"><a href="http://subpos.org/wiki/index.php/SubPos:About" title="SubPos:About">About SubPos</a></li>
								<li id="footer-places-disclaimer"><a href="http://subpos.org/wiki/index.php/SubPos:General_disclaimer" title="SubPos:General disclaimer">Disclaimers</a></li>
							</ul>
									<div style="clear: both;"></div>
		</div>
		

<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":120});});</script>
</body>

<!-- Mirrored from subpos.org/wiki/index.php?title=SubPos:How_it_works&action=history by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 07 Nov 2019 05:39:39 GMT -->
</html>
