<!DOCTYPE html>
<html class="client-nojs" lang="en" dir="ltr">

<!-- Mirrored from subpos.org/wiki/index.php?title=Access_Point_Support&action=history by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 07 Nov 2019 05:39:12 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
<head>
<meta charset="UTF-8"/>
<title>Revision history of "Access Point Support" - SubPos</title>
<script>document.documentElement.className = document.documentElement.className.replace( /(^|\s)client-nojs(\s|$)/, "$1client-js$2" );</script>
<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Access_Point_Support","wgTitle":"Access Point Support","wgCurRevisionId":458,"wgRevisionId":0,"wgArticleId":29,"wgIsArticle":false,"wgIsRedirect":false,"wgAction":"history","wgUserName":null,"wgUserGroups":["*"],"wgCategories":[],"wgBreakFrames":false,"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgMonthNamesShort":["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"wgRelevantPageName":"Access_Point_Support","wgRelevantArticleId":29,"wgRequestId":"XcOqi4TqKysoxXxEhmKnqwAAAgs","wgCSPNonce":false,"wgIsProbablyEditable":false,"wgRelevantPageIsProbablyEditable":false,"wgRestrictionEdit":[],"wgRestrictionMove":[]});mw.loader.state({"site.styles":"ready","noscript":"ready","user.styles":"ready","user":"ready","user.options":"ready","user.tokens":"loading","mediawiki.interface.helpers.styles":"ready","mediawiki.action.history.styles":"ready","mediawiki.special.changeslist":"ready","mediawiki.helplink":"ready","mediawiki.legacy.shared":"ready","mediawiki.legacy.commonPrint":"ready","mediawiki.feedlink":"ready","mediawiki.skinning.interface":"ready","skins.vector.styles":"ready"});mw.loader.implement("user.tokens@0tffind",function($,jQuery,require,module){/*@nomin*/mw.user.tokens.set({"editToken":"+\\","patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
});RLPAGEMODULES=["mediawiki.action.history","site","mediawiki.page.startup","mediawiki.page.ready","mediawiki.searchSuggest","skins.vector.js"];mw.loader.load(RLPAGEMODULES);});</script>
<link rel="stylesheet" href="loadcaad.css?lang=en&amp;modules=mediawiki.action.history.styles%7Cmediawiki.feedlink%2Chelplink%7Cmediawiki.interface.helpers.styles%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.interface%7Cmediawiki.special.changeslist%7Cskins.vector.styles&amp;only=styles&amp;skin=vector"/>
<script async="" src="load3e21.php?lang=en&amp;modules=startup&amp;only=scripts&amp;skin=vector"></script>
<meta name="ResourceLoaderDynamicStyles" content=""/>
<link rel="stylesheet" href="load2f5e.css?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector"/>
<meta name="generator" content="MediaWiki 1.33.0"/>
<meta name="robots" content="noindex,nofollow"/>
<link rel="shortcut icon" href="http://subpos.org/favicon.ico"/>
<link rel="search" type="application/opensearchdescription+xml" href="http://subpos.org/wiki/opensearch_desc.php" title="SubPos (en)"/>
<link rel="EditURI" type="application/rsd+xml" href="http://subpos.org/wiki/api.php?action=rsd"/>
<link rel="alternate" type="application/atom+xml" title="&quot;Access Point Support&quot; Atom feed" href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;feed=atom&amp;action=history"/>
<link rel="alternate" type="application/atom+xml" title="SubPos Atom feed" href="http://subpos.org/wiki/index.php?title=Special:RecentChanges&amp;feed=atom"/>
<!--[if lt IE 9]><script src="/wiki/load.php?lang=en&amp;modules=html5shiv&amp;only=scripts&amp;skin=vector&amp;sync=1"></script><![endif]-->
</head>
<body class="mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject page-Access_Point_Support rootpage-Access_Point_Support skin-vector action-history">
<div id="mw-page-base" class="noprint"></div>
<div id="mw-head-base" class="noprint"></div>
<div id="content" class="mw-body" role="main">
	<a id="top"></a>
	
	<div class="mw-indicators mw-body-content">
<div id="mw-indicator-mw-helplink" class="mw-indicator"><a href="http://meta.wikimedia.org/wiki/Special:MyLanguage/Help:Page_history" target="_blank" class="mw-helplink">Help</a></div>
</div>

	<h1 id="firstHeading" class="firstHeading" lang="en">Revision history of "Access Point Support"</h1>
	
	<div id="bodyContent" class="mw-body-content">
		
		<div id="contentSub"><div class="mw-history-subtitle"><a href="http://subpos.org/wiki/index.php?title=Special:Log&amp;page=Access+Point+Support" title="Special:Log">View logs for this page</a></div></div>
		
		
		
		<div id="jump-to-nav"></div>
		<a class="mw-jump-link" href="#mw-head">Jump to navigation</a>
		<a class="mw-jump-link" href="#p-search">Jump to search</a>
		<div id="mw-content-text"><form action="http://subpos.org/wiki/index.php" method="get" id="mw-history-searchform"><fieldset id="mw-history-search">
<legend>Search for revisions</legend>
<input type="hidden" value="Access_Point_Support" name="title"/>
<input type="hidden" value="history" name="action"/>
<label for="year">From year (and earlier):</label> <input id="year" maxlength="4" size="7" type="number" value="2019" name="year"/> <label for="month">From month (and earlier):</label> <select name="month" id="month" class="mw-month-selector"><option value="-1">all</option>
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option></select> <label for="tagfilter"><a href="http://subpos.org/wiki/index.php/Special:Tags" title="Special:Tags">Tag</a> filter:</label> <input name="tagfilter" size="20" value="" class="mw-tagfilter-input mw-ui-input mw-ui-input-inline" id="tagfilter" /> <input type="submit" value="Show revisions"/>
</fieldset>
</form><div class="mw-history-legend">
<p>Diff selection: Mark the radio boxes of the revisions to compare and hit enter or the button at the bottom.<br />
Legend: <strong>(cur)</strong> = difference with latest revision, <strong>(prev)</strong> = difference with preceding revision, <strong>m</strong> = minor edit.
</p>
</div><form action="http://subpos.org/wiki/index.php" id="mw-history-compare">
<input type="hidden" value="Access_Point_Support" name="title"/>
<input type="hidden" value="historysubmit" name="action"/>
<input type="hidden" value="revision" name="type"/>
<div class="mw-history-compareselectedversions"><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div><ul id="pagehistory">
<li data-mw-revid="458"><span class="mw-history-histlinks mw-changeslist-links"><span>cur</span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=451" title="Access Point Support">prev</a></span></span><input type="radio" value="458" style="visibility:hidden" name="oldid" id="mw-oldid-null" /><input type="radio" value="458" checked="checked" name="diff" id="mw-diff-458" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=458" class="mw-changeslist-date" title="Access Point Support">09:52, 11 June 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">5,667 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="5,667 bytes after change">+164</span>‎</li>
<li data-mw-revid="451"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=451" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=451&amp;oldid=416" title="Access Point Support">prev</a></span></span><input type="radio" value="451" checked="checked" name="oldid" id="mw-oldid-451" /><input type="radio" value="451" name="diff" id="mw-diff-451" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=451" class="mw-changeslist-date" title="Access Point Support">06:11, 20 May 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">5,503 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="5,503 bytes after change">+265</span>‎</li>
<li data-mw-revid="416"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=416" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=416&amp;oldid=415" title="Access Point Support">prev</a></span></span><input type="radio" value="416" name="oldid" id="mw-oldid-416" /><input type="radio" value="416" name="diff" id="mw-diff-416" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=416" class="mw-changeslist-date" title="Access Point Support">06:38, 24 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">5,238 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="5,238 bytes after change">+1</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses"><span dir="auto"><span class="autocomment"><a href="http://subpos.org/wiki/index.php/Access_Point_Support#Troubleshooting" title="Access Point Support">→‎Troubleshooting</a></span></span></span></li>
<li data-mw-revid="415"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=415" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=415&amp;oldid=414" title="Access Point Support">prev</a></span></span><input type="radio" value="415" name="oldid" id="mw-oldid-415" /><input type="radio" value="415" name="diff" id="mw-diff-415" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=415" class="mw-changeslist-date" title="Access Point Support">06:33, 24 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">5,237 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="5,237 bytes after change">+2</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses"><span dir="auto"><span class="autocomment"><a href="http://subpos.org/wiki/index.php/Access_Point_Support#Troubleshooting" title="Access Point Support">→‎Troubleshooting</a></span></span></span></li>
<li data-mw-revid="414"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=414" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=414&amp;oldid=412" title="Access Point Support">prev</a></span></span><input type="radio" value="414" name="oldid" id="mw-oldid-414" /><input type="radio" value="414" name="diff" id="mw-diff-414" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=414" class="mw-changeslist-date" title="Access Point Support">06:32, 24 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">5,235 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="5,235 bytes after change">+52</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses"><span dir="auto"><span class="autocomment"><a href="http://subpos.org/wiki/index.php/Access_Point_Support#Troubleshooting" title="Access Point Support">→‎Troubleshooting</a></span></span></span></li>
<li data-mw-revid="412"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=412" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=412&amp;oldid=411" title="Access Point Support">prev</a></span></span><input type="radio" value="412" name="oldid" id="mw-oldid-412" /><input type="radio" value="412" name="diff" id="mw-diff-412" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=412" class="mw-changeslist-date" title="Access Point Support">05:55, 24 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">5,183 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="5,183 bytes after change">+39</span>‎</li>
<li data-mw-revid="411"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=411" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=411&amp;oldid=410" title="Access Point Support">prev</a></span></span><input type="radio" value="411" name="oldid" id="mw-oldid-411" /><input type="radio" value="411" name="diff" id="mw-diff-411" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=411" class="mw-changeslist-date" title="Access Point Support">05:54, 24 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">5,144 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="5,144 bytes after change">-18</span>‎</li>
<li data-mw-revid="410"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=410" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=410&amp;oldid=409" title="Access Point Support">prev</a></span></span><input type="radio" value="410" name="oldid" id="mw-oldid-410" /><input type="radio" value="410" name="diff" id="mw-diff-410" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=410" class="mw-changeslist-date" title="Access Point Support">05:53, 24 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">5,162 bytes</span> <strong dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="5,162 bytes after change">+736</strong>‎</li>
<li data-mw-revid="409"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=409" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=409&amp;oldid=408" title="Access Point Support">prev</a></span></span><input type="radio" value="409" name="oldid" id="mw-oldid-409" /><input type="radio" value="409" name="diff" id="mw-diff-409" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=409" class="mw-changeslist-date" title="Access Point Support">05:47, 24 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">4,426 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="4,426 bytes after change">+457</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses"><span dir="auto"><span class="autocomment"><a href="http://subpos.org/wiki/index.php/Access_Point_Support#Troubleshooting" title="Access Point Support">→‎Troubleshooting</a></span></span></span></li>
<li data-mw-revid="408"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=408" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=408&amp;oldid=407" title="Access Point Support">prev</a></span></span><input type="radio" value="408" name="oldid" id="mw-oldid-408" /><input type="radio" value="408" name="diff" id="mw-diff-408" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=408" class="mw-changeslist-date" title="Access Point Support">05:40, 24 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,969 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,969 bytes after change">+3</span>‎</li>
<li data-mw-revid="407"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=407" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=407&amp;oldid=406" title="Access Point Support">prev</a></span></span><input type="radio" value="407" name="oldid" id="mw-oldid-407" /><input type="radio" value="407" name="diff" id="mw-diff-407" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=407" class="mw-changeslist-date" title="Access Point Support">05:39, 24 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,966 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,966 bytes after change">+345</span>‎</li>
<li data-mw-revid="406"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=406" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=406&amp;oldid=405" title="Access Point Support">prev</a></span></span><input type="radio" value="406" name="oldid" id="mw-oldid-406" /><input type="radio" value="406" name="diff" id="mw-diff-406" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=406" class="mw-changeslist-date" title="Access Point Support">04:55, 24 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,621 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,621 bytes after change">+13</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses"><span dir="auto"><span class="autocomment"><a href="http://subpos.org/wiki/index.php/Access_Point_Support#Troubleshooting" title="Access Point Support">→‎Troubleshooting</a></span></span></span></li>
<li data-mw-revid="405"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=405" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=405&amp;oldid=401" title="Access Point Support">prev</a></span></span><input type="radio" value="405" name="oldid" id="mw-oldid-405" /><input type="radio" value="405" name="diff" id="mw-diff-405" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=405" class="mw-changeslist-date" title="Access Point Support">04:54, 24 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">3,608 bytes</span> <strong dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="3,608 bytes after change">+775</strong>‎</li>
<li data-mw-revid="401"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=401" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=401&amp;oldid=400" title="Access Point Support">prev</a></span></span><input type="radio" value="401" name="oldid" id="mw-oldid-401" /><input type="radio" value="401" name="diff" id="mw-diff-401" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=401" class="mw-changeslist-date" title="Access Point Support">22:08, 18 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,833 bytes</span> <span dir="ltr" class="mw-plusminus-null mw-diff-bytes" title="2,833 bytes after change">0</span>‎</li>
<li data-mw-revid="400"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=400" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=400&amp;oldid=399" title="Access Point Support">prev</a></span></span><input type="radio" value="400" name="oldid" id="mw-oldid-400" /><input type="radio" value="400" name="diff" id="mw-diff-400" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=400" class="mw-changeslist-date" title="Access Point Support">22:07, 18 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,833 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,833 bytes after change">+300</span>‎</li>
<li data-mw-revid="399"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=399" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=399&amp;oldid=398" title="Access Point Support">prev</a></span></span><input type="radio" value="399" name="oldid" id="mw-oldid-399" /><input type="radio" value="399" name="diff" id="mw-diff-399" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=399" class="mw-changeslist-date" title="Access Point Support">22:04, 18 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,533 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,533 bytes after change">+32</span>‎</li>
<li data-mw-revid="398"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=398" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=398&amp;oldid=396" title="Access Point Support">prev</a></span></span><input type="radio" value="398" name="oldid" id="mw-oldid-398" /><input type="radio" value="398" name="diff" id="mw-diff-398" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=398" class="mw-changeslist-date" title="Access Point Support">22:02, 18 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,501 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,501 bytes after change">+300</span>‎</li>
<li data-mw-revid="396"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=396" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=396&amp;oldid=395" title="Access Point Support">prev</a></span></span><input type="radio" value="396" name="oldid" id="mw-oldid-396" /><input type="radio" value="396" name="diff" id="mw-diff-396" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=396" class="mw-changeslist-date" title="Access Point Support">21:58, 6 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,201 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,201 bytes after change">+134</span>‎</li>
<li data-mw-revid="395"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=395" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=395&amp;oldid=394" title="Access Point Support">prev</a></span></span><input type="radio" value="395" name="oldid" id="mw-oldid-395" /><input type="radio" value="395" name="diff" id="mw-diff-395" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=395" class="mw-changeslist-date" title="Access Point Support">21:56, 6 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,067 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,067 bytes after change">+3</span>‎</li>
<li data-mw-revid="394"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=394" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=394&amp;oldid=392" title="Access Point Support">prev</a></span></span><input type="radio" value="394" name="oldid" id="mw-oldid-394" /><input type="radio" value="394" name="diff" id="mw-diff-394" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=394" class="mw-changeslist-date" title="Access Point Support">21:53, 6 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">2,064 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="2,064 bytes after change">+87</span>‎</li>
<li data-mw-revid="392"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=392" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=392&amp;oldid=391" title="Access Point Support">prev</a></span></span><input type="radio" value="392" name="oldid" id="mw-oldid-392" /><input type="radio" value="392" name="diff" id="mw-diff-392" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=392" class="mw-changeslist-date" title="Access Point Support">21:51, 6 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,977 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,977 bytes after change">+197</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses"><span dir="auto"><span class="autocomment"><a href="http://subpos.org/wiki/index.php/Access_Point_Support#ESP8266_Modules" title="Access Point Support">→‎ESP8266 Modules</a></span></span></span></li>
<li data-mw-revid="391"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=391" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=391&amp;oldid=390" title="Access Point Support">prev</a></span></span><input type="radio" value="391" name="oldid" id="mw-oldid-391" /><input type="radio" value="391" name="diff" id="mw-diff-391" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=391" class="mw-changeslist-date" title="Access Point Support">20:22, 6 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,780 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="1,780 bytes after change">-1</span>‎</li>
<li data-mw-revid="390"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=390" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=390&amp;oldid=389" title="Access Point Support">prev</a></span></span><input type="radio" value="390" name="oldid" id="mw-oldid-390" /><input type="radio" value="390" name="diff" id="mw-diff-390" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=390" class="mw-changeslist-date" title="Access Point Support">20:21, 6 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,781 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,781 bytes after change">+47</span>‎</li>
<li data-mw-revid="389"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=389" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=389&amp;oldid=386" title="Access Point Support">prev</a></span></span><input type="radio" value="389" name="oldid" id="mw-oldid-389" /><input type="radio" value="389" name="diff" id="mw-diff-389" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=389" class="mw-changeslist-date" title="Access Point Support">20:20, 6 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,734 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,734 bytes after change">+250</span>‎</li>
<li data-mw-revid="386"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=386" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=386&amp;oldid=385" title="Access Point Support">prev</a></span></span><input type="radio" value="386" name="oldid" id="mw-oldid-386" /><input type="radio" value="386" name="diff" id="mw-diff-386" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=386" class="mw-changeslist-date" title="Access Point Support">20:12, 6 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,484 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,484 bytes after change">+90</span>‎</li>
<li data-mw-revid="385"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=385" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=385&amp;oldid=384" title="Access Point Support">prev</a></span></span><input type="radio" value="385" name="oldid" id="mw-oldid-385" /><input type="radio" value="385" name="diff" id="mw-diff-385" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=385" class="mw-changeslist-date" title="Access Point Support">19:54, 6 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,394 bytes</span> <span dir="ltr" class="mw-plusminus-null mw-diff-bytes" title="1,394 bytes after change">0</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses"><span dir="auto"><span class="autocomment"><a href="http://subpos.org/wiki/index.php/Access_Point_Support#WRT_Based_Routers_.28e.g._ASUS_DSL-AC68U.29" title="Access Point Support">→‎WRT Based Routers (e.g. ASUS DSL-AC68U)</a></span></span></span></li>
<li data-mw-revid="384"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=384" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=384&amp;oldid=383" title="Access Point Support">prev</a></span></span><input type="radio" value="384" name="oldid" id="mw-oldid-384" /><input type="radio" value="384" name="diff" id="mw-diff-384" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=384" class="mw-changeslist-date" title="Access Point Support">19:49, 6 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,394 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,394 bytes after change">+233</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses"><span dir="auto"><span class="autocomment"><a href="http://subpos.org/wiki/index.php/Access_Point_Support#WRT_Based_Routers_.28e.g._ASUS_DSL-AC68U.29" title="Access Point Support">→‎WRT Based Routers (e.g. ASUS DSL-AC68U)</a></span></span></span></li>
<li data-mw-revid="383"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=383" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=383&amp;oldid=382" title="Access Point Support">prev</a></span></span><input type="radio" value="383" name="oldid" id="mw-oldid-383" /><input type="radio" value="383" name="diff" id="mw-diff-383" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=383" class="mw-changeslist-date" title="Access Point Support">17:36, 6 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,161 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,161 bytes after change">+36</span>‎</li>
<li data-mw-revid="382"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=382" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=382&amp;oldid=381" title="Access Point Support">prev</a></span></span><input type="radio" value="382" name="oldid" id="mw-oldid-382" /><input type="radio" value="382" name="diff" id="mw-diff-382" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=382" class="mw-changeslist-date" title="Access Point Support">17:35, 6 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,125 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,125 bytes after change">+20</span>‎</li>
<li data-mw-revid="381"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=381" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=381&amp;oldid=380" title="Access Point Support">prev</a></span></span><input type="radio" value="381" name="oldid" id="mw-oldid-381" /><input type="radio" value="381" name="diff" id="mw-diff-381" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=381" class="mw-changeslist-date" title="Access Point Support">17:34, 6 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,105 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,105 bytes after change">+37</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses"><span dir="auto"><span class="autocomment"><a href="http://subpos.org/wiki/index.php/Access_Point_Support#WRT_Based_Routers_.28e.g._ASUS_DSL-AC68U.29" title="Access Point Support">→‎WRT Based Routers (e.g. ASUS DSL-AC68U)</a></span></span></span></li>
<li data-mw-revid="380"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=380" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=380&amp;oldid=379" title="Access Point Support">prev</a></span></span><input type="radio" value="380" name="oldid" id="mw-oldid-380" /><input type="radio" value="380" name="diff" id="mw-diff-380" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=380" class="mw-changeslist-date" title="Access Point Support">17:33, 6 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,068 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,068 bytes after change">+25</span>‎</li>
<li data-mw-revid="379"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=379" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=379&amp;oldid=377" title="Access Point Support">prev</a></span></span><input type="radio" value="379" name="oldid" id="mw-oldid-379" /><input type="radio" value="379" name="diff" id="mw-diff-379" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=379" class="mw-changeslist-date" title="Access Point Support">17:32, 6 January 2016</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">1,043 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="1,043 bytes after change">+295</span>‎</li>
<li data-mw-revid="377"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=377" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=377&amp;oldid=376" title="Access Point Support">prev</a></span></span><input type="radio" value="377" name="oldid" id="mw-oldid-377" /><input type="radio" value="377" name="diff" id="mw-diff-377" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=377" class="mw-changeslist-date" title="Access Point Support">01:35, 16 December 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">748 bytes</span> <span dir="ltr" class="mw-plusminus-neg mw-diff-bytes" title="748 bytes after change">-3</span>‎</li>
<li data-mw-revid="376"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=376" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=376&amp;oldid=375" title="Access Point Support">prev</a></span></span><input type="radio" value="376" name="oldid" id="mw-oldid-376" /><input type="radio" value="376" name="diff" id="mw-diff-376" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=376" class="mw-changeslist-date" title="Access Point Support">01:35, 16 December 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">751 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="751 bytes after change">+324</span>‎</li>
<li data-mw-revid="375"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=375" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=375&amp;oldid=374" title="Access Point Support">prev</a></span></span><input type="radio" value="375" name="oldid" id="mw-oldid-375" /><input type="radio" value="375" name="diff" id="mw-diff-375" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=375" class="mw-changeslist-date" title="Access Point Support">01:33, 16 December 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">427 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="427 bytes after change">+63</span>‎</li>
<li data-mw-revid="374"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=374" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=374&amp;oldid=373" title="Access Point Support">prev</a></span></span><input type="radio" value="374" name="oldid" id="mw-oldid-374" /><input type="radio" value="374" name="diff" id="mw-diff-374" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=374" class="mw-changeslist-date" title="Access Point Support">00:57, 9 December 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">364 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="364 bytes after change">+1</span>‎</li>
<li data-mw-revid="373"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=373" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=373&amp;oldid=306" title="Access Point Support">prev</a></span></span><input type="radio" value="373" name="oldid" id="mw-oldid-373" /><input type="radio" value="373" name="diff" id="mw-diff-373" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=373" class="mw-changeslist-date" title="Access Point Support">00:56, 9 December 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">363 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="363 bytes after change">+116</span>‎</li>
<li data-mw-revid="306"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=306" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=306&amp;oldid=243" title="Access Point Support">prev</a></span></span><input type="radio" value="306" name="oldid" id="mw-oldid-306" /><input type="radio" value="306" name="diff" id="mw-diff-306" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=306" class="mw-changeslist-date" title="Access Point Support">10:18, 18 August 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">247 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="247 bytes after change">+154</span>‎</li>
<li data-mw-revid="243"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=243" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=243&amp;oldid=171" title="Access Point Support">prev</a></span></span><input type="radio" value="243" name="oldid" id="mw-oldid-243" /><input type="radio" value="243" name="diff" id="mw-diff-243" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=243" class="mw-changeslist-date" title="Access Point Support">20:43, 19 July 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">93 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="93 bytes after change">+5</span>‎</li>
<li data-mw-revid="171"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=171" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=171&amp;oldid=170" title="Access Point Support">prev</a></span></span><input type="radio" value="171" name="oldid" id="mw-oldid-171" /><input type="radio" value="171" name="diff" id="mw-diff-171" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=171" class="mw-changeslist-date" title="Access Point Support">09:31, 21 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">88 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="88 bytes after change">+25</span>‎</li>
<li data-mw-revid="170"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=170" title="Access Point Support">cur</a></span><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=170&amp;oldid=89" title="Access Point Support">prev</a></span></span><input type="radio" value="170" name="oldid" id="mw-oldid-170" /><input type="radio" value="170" name="diff" id="mw-diff-170" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=170" class="mw-changeslist-date" title="Access Point Support">09:31, 21 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Blecky&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Blecky (page does not exist)"><bdi>Blecky</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Blecky&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Blecky (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Blecky" class="mw-usertoollinks-contribs" title="Special:Contributions/Blecky">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">63 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="63 bytes after change">+11</span>‎</li>
<li data-mw-revid="89"><span class="mw-history-histlinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;diff=458&amp;oldid=89" title="Access Point Support">cur</a></span><span>prev</span></span><input type="radio" value="89" name="oldid" id="mw-oldid-89" /><input type="radio" value="89" name="diff" id="mw-diff-89" /> <a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;oldid=89" class="mw-changeslist-date" title="Access Point Support">07:40, 7 May 2015</a>‎ <span class='history-user'><a href="http://subpos.org/wiki/index.php?title=User:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-userlink" title="User:Subpos-WikiSysop (page does not exist)"><bdi>Subpos-WikiSysop</bdi></a> <span class="mw-usertoollinks mw-changeslist-links"><span><a href="http://subpos.org/wiki/index.php?title=User_talk:Subpos-WikiSysop&amp;action=edit&amp;redlink=1" class="new mw-usertoollinks-talk" title="User talk:Subpos-WikiSysop (page does not exist)">talk</a></span> <span><a href="http://subpos.org/wiki/index.php/Special:Contributions/Subpos-WikiSysop" class="mw-usertoollinks-contribs" title="Special:Contributions/Subpos-WikiSysop">contribs</a></span></span></span>‎ <span class="mw-changeslist-separator"></span> <span class="history-size mw-diff-bytes">52 bytes</span> <span dir="ltr" class="mw-plusminus-pos mw-diff-bytes" title="52 bytes after change">+52</span>‎ <span class="mw-changeslist-separator"></span>  <span class="comment comment--without-parentheses">Created page with &quot;<a href="http://subpos.org/wiki/index.php/Access_Point_Augmentation" title="Access Point Augmentation">Billion BiPAC 7800VDPX</a>&quot;</span></li>
</ul>
<div class="mw-history-compareselectedversions"><input class="historysubmit mw-history-compareselectedversions-button" title="See the differences between the two selected revisions of this page [v]" accesskey="v" type="submit" value="Compare selected revisions"/>
</div></form></div>
		
		<div class="printfooter">Retrieved from "<a dir="ltr" href="http://subpos.org/wiki/index.php/Access_Point_Support">http://subpos.org/wiki/index.php/Access_Point_Support</a>"</div>
		
		<div id="catlinks" class="catlinks catlinks-allhidden" data-mw="interface"></div>
		
		<div class="visualClear"></div>
		
	</div>
</div>

		<div id="mw-navigation">
			<h2>Navigation menu</h2>
			<div id="mw-head">
									<div id="p-personal" role="navigation" aria-labelledby="p-personal-label">
						<h3 id="p-personal-label">Personal tools</h3>
						<ul>
							<li id="pt-login"><a href="http://subpos.org/wiki/index.php?title=Special:UserLogin&amp;returnto=Access+Point+Support&amp;returntoquery=action%3Dhistory" title="You are encouraged to log in; however, it is not mandatory [o]" accesskey="o">Log in</a></li>						</ul>
					</div>
									<div id="left-navigation">
										<div id="p-namespaces" role="navigation" class="vectorTabs" aria-labelledby="p-namespaces-label">
						<h3 id="p-namespaces-label">Namespaces</h3>
						<ul>
							<li id="ca-nstab-main" class="selected"><span><a href="http://subpos.org/wiki/index.php/Access_Point_Support" title="View the content page [c]" accesskey="c">Page</a></span></li><li id="ca-talk" class="new"><span><a href="http://subpos.org/wiki/index.php?title=Talk:Access_Point_Support&amp;action=edit&amp;redlink=1" rel="discussion" title="Discussion about the content page (page does not exist) [t]" accesskey="t">Discussion</a></span></li>						</ul>
					</div>
										<div id="p-variants" role="navigation" class="vectorMenu emptyPortlet" aria-labelledby="p-variants-label">
												<input type="checkbox" class="vectorMenuCheckbox" aria-labelledby="p-variants-label" />
						<h3 id="p-variants-label">
							<span>Variants</span>
						</h3>
						<ul class="menu">
													</ul>
					</div>
									</div>
				<div id="right-navigation">
										<div id="p-views" role="navigation" class="vectorTabs" aria-labelledby="p-views-label">
						<h3 id="p-views-label">Views</h3>
						<ul>
							<li id="ca-view" class="collapsible"><span><a href="http://subpos.org/wiki/index.php/Access_Point_Support">Read</a></span></li><li id="ca-viewsource" class="collapsible"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;action=edit" title="This page is protected.&#10;You can view its source [e]" accesskey="e">View source</a></span></li><li id="ca-history" class="collapsible selected"><span><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;action=history" title="Past revisions of this page [h]" accesskey="h">View history</a></span></li>						</ul>
					</div>
										<div id="p-cactions" role="navigation" class="vectorMenu emptyPortlet" aria-labelledby="p-cactions-label">
						<input type="checkbox" class="vectorMenuCheckbox" aria-labelledby="p-cactions-label" />
						<h3 id="p-cactions-label"><span>More</span></h3>
						<ul class="menu">
													</ul>
					</div>
										<div id="p-search" role="search">
						<h3>
							<label for="searchInput">Search</label>
						</h3>
						<form action="http://subpos.org/wiki/index.php" id="searchform">
							<div id="simpleSearch">
								<input type="search" name="search" placeholder="Search SubPos" title="Search SubPos [f]" accesskey="f" id="searchInput"/><input type="hidden" value="Special:Search" name="title"/><input type="submit" name="fulltext" value="Search" title="Search the pages for this text" id="mw-searchButton" class="searchButton mw-fallbackSearchButton"/><input type="submit" name="go" value="Go" title="Go to a page with this exact name if it exists" id="searchButton" class="searchButton"/>							</div>
						</form>
					</div>
									</div>
			</div>
			<div id="mw-panel">
				<div id="p-logo" role="banner"><a class="mw-wiki-logo" href="http://subpos.org/wiki/index.php/SubPos" title="Visit the main page"></a></div>
						<div class="portal" role="navigation" id="p-navigation" aria-labelledby="p-navigation-label">
			<h3 id="p-navigation-label">Navigation</h3>
			<div class="body">
								<ul>
					<li id="n-mainpage-description"><a href="http://subpos.org/wiki/index.php/SubPos" title="Visit the main page [z]" accesskey="z">Main page</a></li><li id="n-Documentation"><a href="http://subpos.org/wiki/index.php/SubPos:Documentation">Documentation</a></li><li id="n-Software"><a href="http://subpos.org/wiki/index.php/SubPos:Software">Software</a></li><li id="n-Hardware"><a href="http://subpos.org/wiki/index.php/SubPos:Hardware">Hardware</a></li><li id="n-Repository"><a href="http://subpos.org/wiki/index.php/SubPos:Repository">Repository</a></li><li id="n-Main-site"><a href="https://www.subpos.org/" rel="nofollow">Main site</a></li>				</ul>
							</div>
		</div>
			<div class="portal" role="navigation" id="p-tb" aria-labelledby="p-tb-label">
			<h3 id="p-tb-label">Tools</h3>
			<div class="body">
								<ul>
					<li id="t-whatlinkshere"><a href="http://subpos.org/wiki/index.php/Special:WhatLinksHere/Access_Point_Support" title="A list of all wiki pages that link here [j]" accesskey="j">What links here</a></li><li id="t-recentchangeslinked"><a href="http://subpos.org/wiki/index.php/Special:RecentChangesLinked/Access_Point_Support" rel="nofollow" title="Recent changes in pages linked from this page [k]" accesskey="k">Related changes</a></li><li id="feedlinks"><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;feed=atom&amp;action=history" id="feed-atom" rel="alternate" type="application/atom+xml" class="feedlink" title="Atom feed for this page">Atom</a></li><li id="t-specialpages"><a href="http://subpos.org/wiki/index.php/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q">Special pages</a></li><li id="t-info"><a href="http://subpos.org/wiki/index.php?title=Access_Point_Support&amp;action=info" title="More information about this page">Page information</a></li>				</ul>
							</div>
		</div>
				</div>
		</div>
				<div id="footer" role="contentinfo">
						<ul id="footer-places">
								<li id="footer-places-privacy"><a href="http://subpos.org/wiki/index.php/SubPos:Privacy_policy" title="SubPos:Privacy policy">Privacy policy</a></li>
								<li id="footer-places-about"><a href="http://subpos.org/wiki/index.php/SubPos:About" title="SubPos:About">About SubPos</a></li>
								<li id="footer-places-disclaimer"><a href="http://subpos.org/wiki/index.php/SubPos:General_disclaimer" title="SubPos:General disclaimer">Disclaimers</a></li>
							</ul>
									<div style="clear: both;"></div>
		</div>
		

<script>(window.RLQ=window.RLQ||[]).push(function(){mw.config.set({"wgBackendResponseTime":143});});</script>
</body>

<!-- Mirrored from subpos.org/wiki/index.php?title=Access_Point_Support&action=history by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 07 Nov 2019 05:39:12 GMT -->
</html>
